SELECT TOP (10) 
BDRECD,
BDPONO,
BDVNDR,
BDITEM,
BDCRTD,
BDOOQ,
BDOQOO,
BDIUOM,
BDCQOO,
BDTIQR
  FROM [SigmaTB].[dbo].[ITEMHIST]
UNION ALL
SELECT 'Total    ' + CAST(COUNT(*) AS VARCHAR(10))  FROM [SigmaTB].[dbo].[ITEMHIST]


use sigmaTB;

SELECT TOP 10 CALPHA FROM dbo.ITEMHIST
UNION ALL
SELECT 'Total    ' + CAST(COUNT(*) AS VARCHAR(10))  FROM dbo.ITEMHIST;
