/************************************************************************************************
INSERT THE GROUPS PER TABLE
************************************************************************************************/

USE SigmaTB;
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [mrs].[01_tmp](
	[TableCode] [varchar](10) NULL,
	[Prefix] [varchar](10) NULL,
	[TableGroupName] [varchar](200) NULL,
	[TableGroupNumber] [int] NULL
) ON [PRIMARY]
GO

INSERT INTO [mrs].[01_tmp] (
  [Prefix], 
  [TableCode], 
  [TableGroupName], 
  [TableGroupNumber]
)
VALUES
  
('AP801WF','AP','Accounts Payable (AP)',0),
('AP803CSV','AP','Accounts Payable (AP)',0),
('AP803WF','AP','Accounts Payable (AP)',0),
('APBANKCD','AP','Accounts Payable (AP)',0),
('APCHKH','AP','Accounts Payable (AP)',0),
('APCHKR','AP','Accounts Payable (AP)',0),
('APDEBD','AP','Accounts Payable (AP)',0),
('APDEBH','AP','Accounts Payable (AP)',0),
('APDIST','AP','Accounts Payable (AP)',0),
('APEDITR','AP','Accounts Payable (AP)',0),
('APHCOD','AP','Accounts Payable (AP)',0),
('APHIST','AP','Accounts Payable (AP)',0),
('APINV','AP','Accounts Payable (AP)',0),
('APOPEN','AP','Accounts Payable (AP)',0),
('APPRC','AP','Accounts Payable (AP)',0),
('APVEND','AP','Accounts Payable (AP)',0),
('APVHEXC','AP','Accounts Payable (AP)',0),
('APVNDHST','AP','Accounts Payable (AP)',0),
('APVOID','AP','Accounts Payable (AP)',0),
('APWK856','AP','Accounts Payable (AP)',0),
('DBDWRK','DB','Accounts Payable (AP)',0),
('DBHWRK','DB','Accounts Payable (AP)',0),
('WFAP855W','WF','Accounts Payable (AP)',0),
('ARBOLCM','AR','Accounts Receivable (AR)',0),
('ARBTCH','AR','Accounts Receivable (AR)',0),
('ARCASH','AR','Accounts Receivable (AR)',0),
('ARCHEXC','AR','Accounts Receivable (AR)',0),
('ARCUSCHG','AR','Accounts Receivable (AR)',0),
('ARCUSHST','AR','Accounts Receivable (AR)',0),
('ARCUST','AR','Accounts Receivable (AR)',0),
('ARCUST_01','AR','Accounts Receivable (AR)',0),
('ARCUST_40','AR','Accounts Receivable (AR)',0),
('ARCUST_B4','AR','Accounts Receivable (AR)',0),
('ARCUSYEH','AR','Accounts Receivable (AR)',0),
('ARDCRP','AR','Accounts Receivable (AR)',0),
('ARDETAL','AR','Accounts Receivable (AR)',0),
('ARECONCL','AR','Accounts Receivable (AR)',0),
('ARGLTR','AR','Accounts Receivable (AR)',0),
('ARINFO','AR','Accounts Receivable (AR)',0),
('ARLOCK','AR','Accounts Receivable (AR)',0),
('ARPAYHST','AR','Accounts Receivable (AR)',0),
('ARREAS','AR','Accounts Receivable (AR)',0),
('CONTCODE','CONT','Accounts Receivable (AR)',0),
('WFOE895','WF','Accounts Receivable (AR)',0),
('ADDCFTAX','ADD','Additional Charges (ADD)',0),
('ADDCHRG','ADD','Additional Charges (ADD)',0),
('ADDCPTAX','ADD','Additional Charges (ADD)',0),
('ADDCTRAN','ADD','Additional Charges (ADD)',0),
('CHGHST','CH','Additional Charges (ADD)',0),
('BDSEPR','BD','BuyOut',0),
('BDSEPRBH','BD','BuyOut',0),
('CRANAL','CR','Credit',0),
('CRAPLHIS','CR','Credit',0),
('CRCOMMNT','CR','Credit',0),
('CRDETAIL','CR','Credit',0),
('CRHEADER','CR','Credit',0),
('CRHIST','CR','Credit',0),
('CMMAJOR','CM','CreditMemo',0),
('CMMINOR','CM','CreditMemo',0),
('CCLSMT','C','Customer',0),
('CCLSYT','C','Customer',0),
('CLIMITA','C','Customer',0),
('COLCMT','COL','Customer',0),
('CUSINVAD','CUS','Customer',0),
('CUSPRCLS','CUS','Customer',0),
('CUSTADD','CUS','Customer',0),
('CUSTPARN','CUS','Customer',0),
('CUTTHEAD','CUTT','Cutting',0),
('CUTTMTX','CUTT','Cutting',0),
('CUTTOLD','CUTT','Cutting',0),
('SHEETANL','SHEET','CUTTING',0),
('EDICD1','EDI','EDI',0),
('EDICD2','EDI','EDI',0),
('EDICD2A','EDI','EDI',0),
('EDICD3','EDI','EDI',0),
('EDICD4','EDI','EDI',0),
('EDITAB66','EDI','EDI',0),
('EMFORM','EM','Employee',0),
('EMFORM_B4','EM','Employee',0),
('EMLSTDAY','EM','Employee',0),
('EMPPARMS','EMP','Employee',0),
('EMPQUOTE','EMP','Employee',0),
('EMPVALID','EMP','Employee',0),
('EMPLOYE','EMPLOYE','Employee',0),
('GLACCT','GL','General Ledger',0),
('GLDEBCRED','GL','General Ledger',0),
('GLJRBA','GL','General Ledger',0),
('GLJRDT','GL','General Ledger',0),
('GLJRHD','GL','General Ledger',0),
('GLMAJHD','GL','General Ledger',0),
('GLMAST','GL','General Ledger',0),
('GLMASTHST','GL','General Ledger',0),
('GLRPTF','GL','General Ledger',0),
('GLTRANS','GL','General Ledger',0),
('IRECONCL','I','INVENTORY',0),
('REMOTEOH','REMOTE','INVENTORY',0),
('RESTOCK','RESTOCK','INVENTORY',0),
('SICODE','SI','INVENTORY',0),
('WFIN8960','WF','Inventory',0),
('IATRANHS','IA','Inventory Adjustment',0),
('IATRANS','IA','Inventory Adjustment',0),
('ITEMBG','ITEM','ITEM',0),
('ITEMCLS1','ITEM','ITEM',0),
('ITEMCLS2','ITEM','ITEM',0),
('ITEMCLS3','ITEM','ITEM',0),
('ITEMCLSD','ITEM','ITEM',0),
('ITEMHCMT','ITEM','ITEM',0),
('ITEMHIST','ITEM','ITEM',0),
('ITEMMAST','ITEM','ITEM',0),
('ITEMMASTXX','ITEM','ITEM',0),
('ITEMMPLV','ITEM','ITEM',0),
('ITEMONCM','ITEM','ITEM',0),
('ITEMONHD','ITEM','ITEM',0),
('ITEMONHDXX','ITEM','ITEM',0),
('ITEMONSU','ITEM','ITEM',0),
('ITEMRMT','ITEM','ITEM',0),
('ITEMS','ITEM','ITEM',0),
('ITEMSMT','ITEM','ITEM',0),
('ITEMSYT','ITEM','ITEM',0),
('ITEMTAG','ITEM','ITEM',0),
('ITEMTAGB4','ITEM','ITEM',0),
('ITEMTAGLAH','ITEM','ITEM',0),
('ITEMTPHS','ITEM','ITEM',0),
('ITEMTRIF','ITEM','ITEM',0),
('ITEMTUD','ITEM','ITEM',0),
('PRDSBCLS','PRD','ITEM',0),
('PRODFROM','PROD','ITEM',0),
('PRODPROC','PROD','ITEM',0),
('LINECCHG','LINE','LINE',0),
('LINECMNT','LINE','LINE',0),
('LINECNST','LINE','LINE',0),
('LISTHEAT','LIST','MATERIAL PROCESSING',0),
('MAJREJ','MA','MATERIAL PROCESSING',0),
('MACHINE','MACHINE','MATERIAL PROCESSING',0),
('MAINTHIST','MAINT','MATERIAL PROCESSING',0),
('MASSBPC','MASS','MATERIAL PROCESSING',0),
('MASSBPCIFS','MASS','MATERIAL PROCESSING',0),
('MINREJ','MINREJ','MATERIAL PROCESSING',0),
('MNFEST','MNFEST','MATERIAL PROCESSING',0),
('MPDETAIL','MP','MATERIAL PROCESSING',0),
('MPHDRORD','MP','MATERIAL PROCESSING',0),
('MPHSTDET','MP','MATERIAL PROCESSING',0),
('MPHSTHDR','MP','MATERIAL PROCESSING',0),
('MPHSTPRC','MP','MATERIAL PROCESSING',0),
('MPHSTRSK','MP','MATERIAL PROCESSING',0),
('MPHSTUSE','MP','MATERIAL PROCESSING',0),
('MPMISS','MP','MATERIAL PROCESSING',0),
('MPPROFIL','MP','MATERIAL PROCESSING',0),
('MPSETUP','MP','MATERIAL PROCESSING',0),
('MPTRCK','MP','MATERIAL PROCESSING',0),
('MPTRKHST','MP','MATERIAL PROCESSING',0),
('MRTRANS','MR','MATERIAL PROCESSING',0),
('MSWOCMNT','MS','MATERIAL PROCESSING',0),
('MWARCUST','MW','MATERIAL PROCESSING',0),
('MWRESET','MW','MATERIAL PROCESSING',0),
('PHYSTAGM','PHYS','MATERIAL PROCESSING',0),
('OECRRELS','OE','ORDER ENTRY',0),
('OEDETAIL','OE','ORDER ENTRY',0),
('OEHISTRD','OE','ORDER ENTRY',0),
('OEHISTRY','OE','ORDER ENTRY',0),
('OEOPNORD','OE','ORDER ENTRY',0),
('OEPROFIL','OE','ORDER ENTRY',0),
('OESHPINS','OE','ORDER ENTRY',0),
('ORDTRCK','ORD','ORDER ENTRY',0),
('ORDTRHST','ORD','ORDER ENTRY',0),
('BCCHECKS','BC','Other',0),
('BILLDAYS','BILLDAYS','Other',0),
('BOOKINF','BOOKINF','Other',0),
('BUYER','BUYER','Other',0),
('CALENDAR','CALENDAR','Other',0),
('CHEMTAGM','CHEM','Other',0),
('COMPSMO','COMP','Other',0),
('COUNTRY','COUNTRY','Other',0),
('CURRCODE','CURR','Other',0),
('DPPFFD','D','Other',0),
('DISTRAFF','DISTR','Other',0),
('DISTRPRT','DISTR','Other',0),
('DUTYRATE','DUTYRATE','Other',0),
('EMADDTL','EMA','Other',0),
('EMAILLOG','EMAIL','Other',0),
('EMAILTYPE','EMAIL','Other',0),
('ENDUSE','END','Other',0),
('EXCHANGE','EXCHANGE','Other',0),
('EXHTRANS','EXH','Other',0),
('FASTPATH','FASTPAT','Other',0),
('FASTPKEY','FASTPKEY','Other',0),
('FCPARTX','FC','Other',0),
('FLASHINV','FLASHINV','Other',0),
('FLASHRPT','FLASHRPT','Other',0),
('FRACDEC','FRACDEC','Other',0),
('GENCPA','GEN','Other',0),
('IC011SLSP','IC','Other',0),
('IMAGEPDF','IMAGE','Other',0),
('IMAGEPDFB4','IMAGE','Other',0),
('IMGINDX','IMGIN','Other',0),
('IMGPFDS','IMGPF','Other',0),
('INVMILL','INVMILL','Other',0),
('METALFMG','METAL','Other',0),
('OPERINFO','OP','Other',0),
('PARTXMNT','PART','Other',0),
('PARTXRF','PART','Other',0),
('PCTRCK','PCTR','Other',0),
('PRTREQST','PRT','OTHER',0),
('RISKSTAT','RISKSTAT','OTHER',0),
('SFILEDFT','S','OTHER',0),
('SURFCOND','SURF','other',0),
('SYSCNSLM','SYS','other',0),
('TAXEXMPT','TAX','Other',0),
('TERMS','TERMS','other',0),
('TLDETAIL','TL','other',0),
('TRKOUTQ','TRK','other',0),
('USEDBLD','USE','other',0),
('USEDLINE','USE','other',0),
('USETAX','USE','other',0),
('PRCHCHRG','PR','PROCESS CHARGES',0),
('PRCHTQTY','PR','PROCESS CHARGES',0),
('PRCTCHRG','PR','PROCESS CHARGES',0),
('PRCTDIM','PR','PROCESS CHARGES',0),
('POCASHMV','PO','PURCHASE ORDER',0),
('POCHANGE','PO','PURCHASE ORDER',0),
('POCHGLOG','PO','PURCHASE ORDER',0),
('POCMPSMO','PO','PURCHASE ORDER',0),
('POCOMMNT','PO','PURCHASE ORDER',0),
('PODELET','PO','PURCHASE ORDER',0),
('PODETAIL','PO','PURCHASE ORDER',0),
('POHEADER','PO','PURCHASE ORDER',0),
('POHEADERBH','PO','PURCHASE ORDER',0),
('POMKPKLD','PO','PURCHASE ORDER',0),
('PORTNTRY','PO','PURCHASE ORDER',0),
('POSTPRD','PO','PURCHASE ORDER',0),
('POTRCK','PO','PURCHASE ORDER',0),
('POTRKHST','PO','PURCHASE ORDER',0),
('PURCCOMM','PUR','PURCHASE ORDER',0),
('RCPTCOST','RCPT','PURCHASE ORDER',0),
('RCPTHIST','RCPT','PURCHASE ORDER',0),
('RECONHST','RECON','PURCHASE ORDER',0),
('PMATRX','P','sales',0),
('PMATRX_B4','P','sales',0),
('SLSASMT','SL','SALES',0),
('SLSASYT','SL','SALES',0),
('SLSDSCOV','SL','SALES',0),
('SLTML','SL','SALES',0),
('SLTUL','SL','SALES',0),
('SLMNRCAP','SLMN','SALES',0),
('SLMNSUM','SLMN','SALES',0),
('SADAILY','SA','SALES ANALYSIS',0),
('SAGPADJ','SA','SALES ANALYSIS',0),
('SALESBUD','SA','SALES ANALYSIS',0),
('SALESMAN','SA','SALES ANALYSIS',0),
('SALESOBJ','SA','SALES ANALYSIS',0),
('SALESTAX','SA','SALES ANALYSIS',0),
('SAMTHLY','SA','SALES ANALYSIS',0),
('SPDETAIL','SP','SERVICE PURCHASE',0),
('SPHEADER','SP','SERVICE PURCHASE',0),
('SPOTRCK','SP','SERVICE PURCHASE',0),
('DELTRACK','DEL','Shipment',0),
('FCXREF','FC','Shipment',0),
('FRECONCL','FRECONCL','Shipment',0),
('FRTHST','FRTHST','Shipment',0),
('PICKDTL','PICK','Shipment',0),
('SHIPADR','SHIP','Shipment',0),
('SHIPBCKG','SHIP','Shipment',0),
('SHIPDISP','SHIP','Shipment',0),
('SHIPMAST','SHIP','Shipment',0),
('SHPINST','SHPI','Shipment',0),
('SHSUMM','SHSU','Shipment',0),
('UDFDATAL','UD','System',0),
('UDFDATAT','UD','System',0),
('UDFDATAV','UD','System',0),
('UPINPF','UP','System',0),
('UPLOADPI','UPLOAD','System',0),
('WEBCUST','WEB','System',0),
('X820OAB','X','System',0),
('X820OAD','X','System',0),
('X820OAH','X','System',0),
('TAGBUILD','TAG','TAG',0),
('TAGCMNT','TAG','TAG',0),
('TAGLOCMV','TAG','TAG',0),
('TAGTRAN','TAG','TAG',0),
('ACHINFO','ACH','Vendor Management (VEND)',0),
('VENDINST','VEND','Vendor Management (VEND)',0),
('VENDMAIL','VEND','Vendor Management (VEND)',0),
('VENDPRFM','VEND','Vendor Management (VEND)',0),
('VENDQUAL','VEND','Vendor Management (VEND)',0),
('VENDREMT','VEND','Vendor Management (VEND)',0),
('VENDSHIP','VEND','Vendor Management (VEND)',0),
('VNDREQHD','VNDR','Vendor Management (VEND)',0),
('WHMPTRC','WH','Warehouse',0),
('WHOLORCH','WH','Warehouse',0),
('WHORDTRC','WH','Warehouse',0),
('WHPCTRC','WH','Warehouse',0),
('WHPOTRC','WH','Warehouse',0),
('WHSEMCOD','WH','Warehouse',0),
('WHTRCKEM','WH','Warehouse',0),
('WFFAXEMAIL','WF','Workfile',0);

  