

SELECT
    GLRECD.GLREXT AS Ext,
    GLRECD.GLCO + GLRECD.GLDS + GLRECD.GLCS AS [CO DS CS],
    GLRECD.GLFS AS FS,
    GLRECD.GLACCT AS Account,
    GLACCT.GACDES AS Title,
    GLRECD.GLPD AS Period,
    GLRECD.GLDESC AS [Transaction],
    GLRECD.GLREF AS Reference,
    GLRECD.GLAMTQ AS Amount,
    GLRECD.GLAPPL AS APP,
    GLRECD.GLPRGM AS Prgm,
    GLRECD.GLUSER AS [User],
    GLRECD.GLRPTY AS Related,
    GLRECD.GLRP# AS [#],
    GLRECD.GLTRNT AS Tran,
    GLRECD.GLTYPE AS Type,
    GLRECD.GLTRDS AS Dist,
    GLRECD.GLTRN# AS Document,
    GLRECD.GLPOST AS Posting,
    GLRECD.GLSYST AS System,
    GLRECD.GLCUST AS Custmr
FROM GLRECD
LEFT JOIN GLACCT ON GLRECD.GLACCT = GLACCT.GLACCT
WHERE GLRECD.GLPD BETWEEN 2400 AND 2412
ORDER BY GLRECD.GLACCT, GLRECD.GLPOST;
