-- SQL DDL generated from CSV with INFERRED Inline Keys
-- WARNING: Primary and Foreign Keys are GUESSED based on naming conventions and column suffixes.
--          Thoroughly review and CORRECT this schema in your ERD tool (DBSchema).

-- Table: APDEBD
CREATE TABLE "APDEBD" (
    "APDEBD_ID" INT,
    "V2BTCH" VARCHAR(255),
    "V2TRAN" VARCHAR(255),
    PRIMARY KEY ("APDEBD_ID") -- Generic PK (NEEDS VALIDATION!)
);

-- Table: APVEND
CREATE TABLE "APVEND" (
    "APVEND_ID" INT,
    "VCCUST" VARCHAR(255),
    "VCUST" VARCHAR(255),
    "VFLAG3" VARCHAR(255),
    "VFLAG5" VARCHAR(255),
    "VFLAG6" VARCHAR(255),
    PRIMARY KEY ("APVEND_ID") -- Generic PK (NEEDS VALIDATION!),
    FOREIGN KEY ("VCCUST") REFERENCES "ARCUST" ("CCUST") -- Inferred FK (Suffix: 'CUST'),
    FOREIGN KEY ("VCUST") REFERENCES "ARCUST" ("CCUST") -- Inferred FK (Suffix: 'CUST')
);

-- Table: APWK856
CREATE TABLE "APWK856" (
    "APWK856_ID" INT,
    "WHBTCH" VARCHAR(255),
    "WHTRAN" VARCHAR(255),
    PRIMARY KEY ("APWK856_ID") -- Generic PK (NEEDS VALIDATION!)
);

-- Table: ARCUST
CREATE TABLE "ARCUST" (
    "CADDR1" VARCHAR(255),
    "CADDR2" VARCHAR(255),
    "CADDR3" VARCHAR(255),
    "CCUST" VARCHAR(255),
    PRIMARY KEY ("CCUST")
);

-- Table: CCLSMT
CREATE TABLE "CCLSMT" (
    "CCLSMT_ID" INT,
    "MCFISD" VARCHAR(255),
    "MCFISS" VARCHAR(255),
    PRIMARY KEY ("CCLSMT_ID") -- Generic PK (NEEDS VALIDATION!)
);

-- Table: CCLSYT
CREATE TABLE "CCLSYT" (
    "CCLSYT_ID" INT,
    "YCFISD" VARCHAR(255),
    "YCFISS" VARCHAR(255),
    PRIMARY KEY ("CCLSYT_ID") -- Generic PK (NEEDS VALIDATION!)
);

-- Table: CRCOMMNT
CREATE TABLE "CRCOMMNT" (
    "CRCOMMNT_ID" INT,
    "C7CUST" VARCHAR(255),
    PRIMARY KEY ("CRCOMMNT_ID") -- Generic PK (NEEDS VALIDATION!),
    FOREIGN KEY ("C7CUST") REFERENCES "ARCUST" ("CCUST") -- Inferred FK (Suffix: 'CUST')
);

-- Table: CRDETAIL
CREATE TABLE "CRDETAIL" (
    "CRDETAIL_ID" INT,
    "CRDDST" VARCHAR(255),
    "CRDLIN" VARCHAR(255),
    PRIMARY KEY ("CRDETAIL_ID") -- Generic PK (NEEDS VALIDATION!)
);

-- Table: CRHEADER
CREATE TABLE "CRHEADER" (
    "CRHEADER_ID" INT,
    "CRHDST" VARCHAR(255),
    PRIMARY KEY ("CRHEADER_ID") -- Generic PK (NEEDS VALIDATION!)
);

-- Table: DELTRACK
CREATE TABLE "DELTRACK" (
    "DELTRACK_ID" INT,
    "DPACTM" TIMESTAMP,
    "DPCDIS" VARCHAR(255),
    "DPCUST" VARCHAR(255),
    "DPECTM" TIMESTAMP,
    "DPOLIN" VARCHAR(255),
    "DPRTYP" VARCHAR(255),
    "DPTRCD" VARCHAR(255),
    PRIMARY KEY ("DELTRACK_ID") -- Generic PK (NEEDS VALIDATION!),
    FOREIGN KEY ("DPCUST") REFERENCES "ARCUST" ("CCUST") -- Inferred FK (Suffix: 'CUST')
);

-- Table: DPPFFD
CREATE TABLE "DPPFFD" (
    "DPPFFD_ID" INT,
    "QBFDDS" VARCHAR(255),
    PRIMARY KEY ("DPPFFD_ID") -- Generic PK (NEEDS VALIDATION!)
);

-- Table: EMLSTDAY
CREATE TABLE "EMLSTDAY" (
    "EMLSTDAY_ID" INT,
    "ELDIST" VARCHAR(255),
    PRIMARY KEY ("EMLSTDAY_ID") -- Generic PK (NEEDS VALIDATION!),
    FOREIGN KEY ("ELDIST") REFERENCES "GLMAST" ("GLMAST_ID") -- Inferred FK (Suffix: 'DIST')
);

-- Table: FRTHST
CREATE TABLE "FRTHST" (
    "FRTHST_ID" INT,
    "FSBOL" VARCHAR(255),
    "FSBTCH" VARCHAR(255),
    "FSSEQ" DECIMAL(18, 4),
    "FSTRAN" VARCHAR(255),
    PRIMARY KEY ("FRTHST_ID") -- Generic PK (NEEDS VALIDATION!)
);

-- Table: GLJRBA
CREATE TABLE "GLJRBA" (
    "GLJRBA_ID" INT,
    "GBBAMT" DECIMAL(18, 4),
    PRIMARY KEY ("GLJRBA_ID") -- Generic PK (NEEDS VALIDATION!)
);

-- Table: GLMAST
CREATE TABLE "GLMAST" (
    "GLMAST_ID" INT,
    "GMDIST" VARCHAR(255),
    PRIMARY KEY ("GLMAST_ID") -- Generic PK (NEEDS VALIDATION!)
);

-- Table: GLTRANS
CREATE TABLE "GLTRANS" (
    "GLTRANS_ID" INT,
    "GLAPTR" VARCHAR(255),
    "GLBTCH" VARCHAR(255),
    "GLCDIS" VARCHAR(255),
    "GLCUST" VARCHAR(255),
    "GLDIST" VARCHAR(255),
    "GLTYPE" VARCHAR(255),
    PRIMARY KEY ("GLTRANS_ID") -- Generic PK (NEEDS VALIDATION!),
    FOREIGN KEY ("GLCUST") REFERENCES "ARCUST" ("CCUST") -- Inferred FK (Suffix: 'CUST'),
    FOREIGN KEY ("GLDIST") REFERENCES "GLMAST" ("GLMAST_ID") -- Inferred FK (Suffix: 'DIST')
);

-- Table: IATRANHS
CREATE TABLE "IATRANHS" (
    "IABAT#" INT,
    "IABOL" VARCHAR(255),
    "IACAR#" VARCHAR(255),
    "IADIST" VARCHAR(255),
    "IAPODI" VARCHAR(255),
    "IAPOLN" VARCHAR(255),
    PRIMARY KEY ("IABAT#"),
    FOREIGN KEY ("IADIST") REFERENCES "GLMAST" ("GLMAST_ID") -- Inferred FK (Suffix: 'DIST')
);

-- Table: IATRANS
CREATE TABLE "IATRANS" (
    "IABAT#" INT,
    "IABOL" VARCHAR(255),
    "IACAR#" VARCHAR(255),
    "IADIST" VARCHAR(255),
    "IAPODI" VARCHAR(255),
    "IAPOLN" VARCHAR(255),
    PRIMARY KEY ("IABAT#"),
    FOREIGN KEY ("IADIST") REFERENCES "GLMAST" ("GLMAST_ID") -- Inferred FK (Suffix: 'DIST')
);

-- Table: IMAGEPDF
CREATE TABLE "IMAGEPDF" (
    "DATENT" VARCHAR(255),
    "DATUPD" VARCHAR(255),
    "IMAGE" VARCHAR(255),
    "ITHEAT" VARCHAR(255),
    "SDDIST" VARCHAR(255),
    "TYPIMG" VARCHAR(255),
    "VOINV#" INT,
    PRIMARY KEY ("VOINV#"),
    FOREIGN KEY ("SDDIST") REFERENCES "GLMAST" ("GLMAST_ID") -- Inferred FK (Suffix: 'DIST'),
    FOREIGN KEY ("ITHEAT") REFERENCES "LISTHEAT" ("LISTHEAT_ID") -- Inferred FK (Suffix: 'HEAT')
);

-- Table: IMAGEPDFB4
CREATE TABLE "IMAGEPDFB4" (
    "DATENT" VARCHAR(255),
    "DATUPD" VARCHAR(255),
    "IMAGE" VARCHAR(255),
    "ITHEAT" VARCHAR(255),
    "SDDIST" VARCHAR(255),
    "TYPIMG" VARCHAR(255),
    "VOINV#" INT,
    PRIMARY KEY ("VOINV#"),
    FOREIGN KEY ("SDDIST") REFERENCES "GLMAST" ("GLMAST_ID") -- Inferred FK (Suffix: 'DIST'),
    FOREIGN KEY ("ITHEAT") REFERENCES "LISTHEAT" ("LISTHEAT_ID") -- Inferred FK (Suffix: 'HEAT')
);

-- Table: INVMILL
CREATE TABLE "INVMILL" (
    "INVMILL_ID" INT,
    "MICTRY" VARCHAR(255),
    PRIMARY KEY ("INVMILL_ID") -- Generic PK (NEEDS VALIDATION!)
);

-- Table: ITEMBG
CREATE TABLE "ITEMBG" (
    "ITEMBG_ID" INT,
    "IMCSMO" VARCHAR(255),
    PRIMARY KEY ("ITEMBG_ID") -- Generic PK (NEEDS VALIDATION!)
);

-- Table: ITEMCLS3
CREATE TABLE "ITEMCLS3" (
    "ITEMCLS3_ID" INT,
    "I3CSMO" VARCHAR(255),
    PRIMARY KEY ("ITEMCLS3_ID") -- Generic PK (NEEDS VALIDATION!)
);

-- Table: ITEMHIST
CREATE TABLE "ITEMHIST" (
    "IHCUST" VARCHAR(255),
    "IHDIST" VARCHAR(255),
    "IHDOC#" INT,
    "IHHEAT" VARCHAR(255),
    PRIMARY KEY ("IHDOC#"),
    FOREIGN KEY ("IHCUST") REFERENCES "ARCUST" ("CCUST") -- Inferred FK (Suffix: 'CUST'),
    FOREIGN KEY ("IHDIST") REFERENCES "GLMAST" ("GLMAST_ID") -- Inferred FK (Suffix: 'DIST'),
    FOREIGN KEY ("IHHEAT") REFERENCES "LISTHEAT" ("LISTHEAT_ID") -- Inferred FK (Suffix: 'HEAT')
);

-- Table: ITEMMAST
CREATE TABLE "ITEMMAST" (
    "ITEMMAST_ID" INT,
    "IMCSMO" VARCHAR(255),
    "IMCUST" VARCHAR(255),
    PRIMARY KEY ("ITEMMAST_ID") -- Generic PK (NEEDS VALIDATION!),
    FOREIGN KEY ("IMCUST") REFERENCES "ARCUST" ("CCUST") -- Inferred FK (Suffix: 'CUST')
);

-- Table: ITEMMASTXX
CREATE TABLE "ITEMMASTXX" (
    "ITEMMASTXX_ID" INT,
    "IMCSMO" VARCHAR(255),
    PRIMARY KEY ("ITEMMASTXX_ID") -- Generic PK (NEEDS VALIDATION!)
);

-- Table: ITEMONCM
CREATE TABLE "ITEMONCM" (
    "ITEMONCM_ID" INT,
    "I5DIST" VARCHAR(255),
    PRIMARY KEY ("ITEMONCM_ID") -- Generic PK (NEEDS VALIDATION!),
    FOREIGN KEY ("I5DIST") REFERENCES "GLMAST" ("GLMAST_ID") -- Inferred FK (Suffix: 'DIST')
);

-- Table: ITEMONHD
CREATE TABLE "ITEMONHD" (
    "ITEMONHD_ID" INT,
    "IOCUST" VARCHAR(255),
    "IODIST" VARCHAR(255),
    PRIMARY KEY ("ITEMONHD_ID") -- Generic PK (NEEDS VALIDATION!),
    FOREIGN KEY ("IOCUST") REFERENCES "ARCUST" ("CCUST") -- Inferred FK (Suffix: 'CUST'),
    FOREIGN KEY ("IODIST") REFERENCES "GLMAST" ("GLMAST_ID") -- Inferred FK (Suffix: 'DIST')
);

-- Table: ITEMTAG
CREATE TABLE "ITEMTAG" (
    "ITEMTAG_ID" INT,
    "ITCDIS" VARCHAR(255),
    "ITCPRT" VARCHAR(255),
    "ITCTAG" VARCHAR(255),
    "ITCUST" VARCHAR(255),
    "ITDIST" VARCHAR(255),
    "ITFLG4" VARCHAR(255),
    "ITFLG5" VARCHAR(255),
    "ITHEAT" VARCHAR(255),
    "ITMLIN" VARCHAR(255),
    "ITPRNT" VARCHAR(255),
    "ITSHAP" VARCHAR(255),
    PRIMARY KEY ("ITEMTAG_ID") -- Generic PK (NEEDS VALIDATION!),
    FOREIGN KEY ("ITCUST") REFERENCES "ARCUST" ("CCUST") -- Inferred FK (Suffix: 'CUST'),
    FOREIGN KEY ("ITDIST") REFERENCES "GLMAST" ("GLMAST_ID") -- Inferred FK (Suffix: 'DIST'),
    FOREIGN KEY ("ITHEAT") REFERENCES "LISTHEAT" ("LISTHEAT_ID") -- Inferred FK (Suffix: 'HEAT')
);

-- Table: ITEMTPHS
CREATE TABLE "ITEMTPHS" (
    "ITEMTPHS_ID" INT,
    "TPULIN" VARCHAR(255),
    PRIMARY KEY ("ITEMTPHS_ID") -- Generic PK (NEEDS VALIDATION!)
);

-- Table: LINECCHG
CREATE TABLE "LINECCHG" (
    "LINECCHG_ID" INT,
    "LCHCMT" VARCHAR(255),
    "LCHDST" VARCHAR(255),
    "LCHOTP" VARCHAR(255),
    PRIMARY KEY ("LINECCHG_ID") -- Generic PK (NEEDS VALIDATION!)
);

-- Table: LINECMNT
CREATE TABLE "LINECMNT" (
    "LINECMNT_ID" INT,
    "LCCMNT" VARCHAR(255),
    "LCDIST" VARCHAR(255),
    PRIMARY KEY ("LINECMNT_ID") -- Generic PK (NEEDS VALIDATION!),
    FOREIGN KEY ("LCDIST") REFERENCES "GLMAST" ("GLMAST_ID") -- Inferred FK (Suffix: 'DIST')
);

-- Table: LINECNST
CREATE TABLE "LINECNST" (
    "LINECNST_ID" INT,
    "LSAPPL" VARCHAR(255),
    "LSCCOD" VARCHAR(255),
    "LSCMNT" VARCHAR(255),
    "LSCODE" VARCHAR(255),
    "LSPRNT" VARCHAR(255),
    "LSREQR" VARCHAR(255),
    PRIMARY KEY ("LINECNST_ID") -- Generic PK (NEEDS VALIDATION!)
);

-- Table: LISTHEAT
CREATE TABLE "LISTHEAT" (
    "LISTHEAT_ID" INT,
    "LHDIST" VARCHAR(255),
    "LHHEAT" VARCHAR(255),
    PRIMARY KEY ("LISTHEAT_ID") -- Generic PK (NEEDS VALIDATION!),
    FOREIGN KEY ("LHDIST") REFERENCES "GLMAST" ("GLMAST_ID") -- Inferred FK (Suffix: 'DIST')
);

-- Table: MPDETAIL
CREATE TABLE "MPDETAIL" (
    "MPDETAIL_ID" INT,
    "MDCDST" VARCHAR(255),
    "MDCUST" VARCHAR(255),
    "MDDIST" VARCHAR(255),
    "MDMLIN" VARCHAR(255),
    "MDSHAP" VARCHAR(255),
    "MDTYPE" VARCHAR(255),
    PRIMARY KEY ("MPDETAIL_ID") -- Generic PK (NEEDS VALIDATION!),
    FOREIGN KEY ("MDCUST") REFERENCES "ARCUST" ("CCUST") -- Inferred FK (Suffix: 'CUST'),
    FOREIGN KEY ("MDDIST") REFERENCES "GLMAST" ("GLMAST_ID") -- Inferred FK (Suffix: 'DIST')
);

-- Table: MPHDRORD
CREATE TABLE "MPHDRORD" (
    "MHCSTD" VARCHAR(255),
    "MHCUS#" INT,
    "MHCUST" VARCHAR(255),
    "MHDIST" VARCHAR(255),
    "MHECS#" VARCHAR(255),
    "MHGMPC" VARCHAR(255),
    "MHTYPE" VARCHAR(255),
    PRIMARY KEY ("MHCUS#"),
    FOREIGN KEY ("MHCUST") REFERENCES "ARCUST" ("CCUST") -- Inferred FK (Suffix: 'CUST'),
    FOREIGN KEY ("MHDIST") REFERENCES "GLMAST" ("GLMAST_ID") -- Inferred FK (Suffix: 'DIST')
);

-- Table: MPHSTDET
CREATE TABLE "MPHSTDET" (
    "MPHSTDET_ID" INT,
    "MDCDST" VARCHAR(255),
    "MDCUST" VARCHAR(255),
    "MDDIST" VARCHAR(255),
    "MDMLIN" VARCHAR(255),
    "MDSHAP" VARCHAR(255),
    "MDTYPE" VARCHAR(255),
    PRIMARY KEY ("MPHSTDET_ID") -- Generic PK (NEEDS VALIDATION!),
    FOREIGN KEY ("MDCUST") REFERENCES "ARCUST" ("CCUST") -- Inferred FK (Suffix: 'CUST'),
    FOREIGN KEY ("MDDIST") REFERENCES "GLMAST" ("GLMAST_ID") -- Inferred FK (Suffix: 'DIST')
);

-- Table: MPHSTHDR
CREATE TABLE "MPHSTHDR" (
    "MHCSTD" VARCHAR(255),
    "MHCUS#" INT,
    "MHCUST" VARCHAR(255),
    "MHDIST" VARCHAR(255),
    "MHGMPC" VARCHAR(255),
    "MHTYPE" VARCHAR(255),
    PRIMARY KEY ("MHCUS#"),
    FOREIGN KEY ("MHCUST") REFERENCES "ARCUST" ("CCUST") -- Inferred FK (Suffix: 'CUST'),
    FOREIGN KEY ("MHDIST") REFERENCES "GLMAST" ("GLMAST_ID") -- Inferred FK (Suffix: 'DIST')
);

-- Table: MPHSTPRC
CREATE TABLE "MPHSTPRC" (
    "MPHSTPRC_ID" INT,
    "PKIBLN" VARCHAR(255),
    "PKODST" VARCHAR(255),
    "PKOMLN" VARCHAR(255),
    PRIMARY KEY ("MPHSTPRC_ID") -- Generic PK (NEEDS VALIDATION!)
);

-- Table: MPHSTRSK
CREATE TABLE "MPHSTRSK" (
    "RLASL#" INT,
    "RLDIST" VARCHAR(255),
    "RLMLIN" VARCHAR(255),
    "RLULIN" VARCHAR(255),
    PRIMARY KEY ("RLASL#"),
    FOREIGN KEY ("RLDIST") REFERENCES "GLMAST" ("GLMAST_ID") -- Inferred FK (Suffix: 'DIST')
);

-- Table: MPHSTUSE
CREATE TABLE "MPHSTUSE" (
    "MPHSTUSE_ID" INT,
    "ULCDIS" VARCHAR(255),
    "ULCUST" VARCHAR(255),
    "ULDIST" VARCHAR(255),
    "ULIBLN" VARCHAR(255),
    "ULINVR" VARCHAR(255),
    "ULLKOO" VARCHAR(255),
    "ULLKOR" VARCHAR(255),
    "ULMLIN" VARCHAR(255),
    "ULPBOL" VARCHAR(255),
    "ULSHAP" VARCHAR(255),
    "ULSQTY" DECIMAL(18, 4),
    "ULTBOL" VARCHAR(255),
    "ULTFT" VARCHAR(255),
    "ULTKG" VARCHAR(255),
    "ULTLBS" VARCHAR(255),
    "ULTMTR" VARCHAR(255),
    "ULTPCS" VARCHAR(255),
    "ULTSFT" VARCHAR(255),
    "ULUQTY" DECIMAL(18, 4),
    "ULWBOL" VARCHAR(255),
    PRIMARY KEY ("MPHSTUSE_ID") -- Generic PK (NEEDS VALIDATION!),
    FOREIGN KEY ("ULCUST") REFERENCES "ARCUST" ("CCUST") -- Inferred FK (Suffix: 'CUST'),
    FOREIGN KEY ("ULDIST") REFERENCES "GLMAST" ("GLMAST_ID") -- Inferred FK (Suffix: 'DIST')
);

-- Table: MPPROFIL
CREATE TABLE "MPPROFIL" (
    "MPPROFIL_ID" INT,
    "MFBOL" VARCHAR(255),
    "MFDIST" VARCHAR(255),
    "MFFRTO" VARCHAR(255),
    PRIMARY KEY ("MPPROFIL_ID") -- Generic PK (NEEDS VALIDATION!),
    FOREIGN KEY ("MFDIST") REFERENCES "GLMAST" ("GLMAST_ID") -- Inferred FK (Suffix: 'DIST')
);

-- Table: MPTRCK
CREATE TABLE "MPTRCK" (
    "MPTRCK_ID" INT,
    "MTMLIN" VARCHAR(255),
    PRIMARY KEY ("MPTRCK_ID") -- Generic PK (NEEDS VALIDATION!)
);

-- Table: MPTRKHST
CREATE TABLE "MPTRKHST" (
    "MPTRKHST_ID" INT,
    "MTHCOM" VARCHAR(255),
    "MTHDST" VARCHAR(255),
    "MTHLIN" VARCHAR(255),
    PRIMARY KEY ("MPTRKHST_ID") -- Generic PK (NEEDS VALIDATION!)
);

-- Table: MWRESET
CREATE TABLE "MWRESET" (
    "MWBOL#" INT,
    PRIMARY KEY ("MWBOL#")
);

-- Table: OEDETAIL
CREATE TABLE "OEDETAIL" (
    "OEDETAIL_ID" INT,
    "ODCLIN" VARCHAR(255),
    "ODCONT" VARCHAR(255),
    "ODCUST" VARCHAR(255),
    "ODHEAT" VARCHAR(255),
    "ODSHAP" VARCHAR(255),
    "ODTYPE" VARCHAR(255),
    PRIMARY KEY ("OEDETAIL_ID") -- Generic PK (NEEDS VALIDATION!),
    FOREIGN KEY ("ODCUST") REFERENCES "ARCUST" ("CCUST") -- Inferred FK (Suffix: 'CUST'),
    FOREIGN KEY ("ODHEAT") REFERENCES "LISTHEAT" ("LISTHEAT_ID") -- Inferred FK (Suffix: 'HEAT')
);

-- Table: OEHISTRD
CREATE TABLE "OEHISTRD" (
    "OEHISTRD_ID" INT,
    "DHCUST" VARCHAR(255),
    "DHDIST" VARCHAR(255),
    "DHSHAP" VARCHAR(255),
    "DHTYPE" VARCHAR(255),
    PRIMARY KEY ("OEHISTRD_ID") -- Generic PK (NEEDS VALIDATION!),
    FOREIGN KEY ("DHCUST") REFERENCES "ARCUST" ("CCUST") -- Inferred FK (Suffix: 'CUST'),
    FOREIGN KEY ("DHDIST") REFERENCES "GLMAST" ("GLMAST_ID") -- Inferred FK (Suffix: 'DIST')
);

-- Table: OEHISTRY
CREATE TABLE "OEHISTRY" (
    "OEHISTRY_ID" INT,
    "OHBODI" VARCHAR(255),
    "OHCUST" VARCHAR(255),
    "OHGMPC" VARCHAR(255),
    "OHORDR" VARCHAR(255),
    PRIMARY KEY ("OEHISTRY_ID") -- Generic PK (NEEDS VALIDATION!),
    FOREIGN KEY ("OHCUST") REFERENCES "ARCUST" ("CCUST") -- Inferred FK (Suffix: 'CUST'),
    FOREIGN KEY ("OHORDR") REFERENCES "OEOPNORD" ("OOORDR") -- Inferred FK (Suffix: 'ORDR')
);

-- Table: OEOPNORD
CREATE TABLE "OEOPNORD" (
    "OOCNTR" VARCHAR(255),
    "OOCUST" VARCHAR(255),
    "OODRVR" VARCHAR(255),
    "OOGMPC" VARCHAR(255),
    "OOORDR" VARCHAR(255),
    "OOTYPE" VARCHAR(255),
    PRIMARY KEY ("OOORDR"),
    FOREIGN KEY ("OOCUST") REFERENCES "ARCUST" ("CCUST") -- Inferred FK (Suffix: 'CUST')
);

-- Table: OEPROFIL
CREATE TABLE "OEPROFIL" (
    "OEPROFIL_ID" INT,
    "OPBOL" VARCHAR(255),
    "OPFRTO" VARCHAR(255),
    PRIMARY KEY ("OEPROFIL_ID") -- Generic PK (NEEDS VALIDATION!)
);

-- Table: ORDTRCK
CREATE TABLE "ORDTRCK" (
    "ORDTRCK_ID" INT,
    "OTCDIS" VARCHAR(255),
    "OTCUST" VARCHAR(255),
    "OTORDR" VARCHAR(255),
    PRIMARY KEY ("ORDTRCK_ID") -- Generic PK (NEEDS VALIDATION!),
    FOREIGN KEY ("OTCUST") REFERENCES "ARCUST" ("CCUST") -- Inferred FK (Suffix: 'CUST'),
    FOREIGN KEY ("OTORDR") REFERENCES "OEOPNORD" ("OOORDR") -- Inferred FK (Suffix: 'ORDR')
);

-- Table: ORDTRHST
CREATE TABLE "ORDTRHST" (
    "ORDTRHST_ID" INT,
    "OTHCOM" VARCHAR(255),
    "OTHORD" VARCHAR(255),
    "OTTMSP" VARCHAR(255),
    PRIMARY KEY ("ORDTRHST_ID") -- Generic PK (NEEDS VALIDATION!)
);

-- Table: POCHGLOG
CREATE TABLE "POCHGLOG" (
    "POCHGLOG_ID" INT,
    "LGDIST" VARCHAR(255),
    PRIMARY KEY ("POCHGLOG_ID") -- Generic PK (NEEDS VALIDATION!),
    FOREIGN KEY ("LGDIST") REFERENCES "GLMAST" ("GLMAST_ID") -- Inferred FK (Suffix: 'DIST')
);

-- Table: POCMPSMO
CREATE TABLE "POCMPSMO" (
    "POCMPSMO_ID" INT,
    "P4COMM" VARCHAR(255),
    "P4DIST" VARCHAR(255),
    PRIMARY KEY ("POCMPSMO_ID") -- Generic PK (NEEDS VALIDATION!),
    FOREIGN KEY ("P4DIST") REFERENCES "GLMAST" ("GLMAST_ID") -- Inferred FK (Suffix: 'DIST')
);

-- Table: PODETAIL
CREATE TABLE "PODETAIL" (
    "PODETAIL_ID" INT,
    "BDBOL" VARCHAR(255),
    "BDCSMO" VARCHAR(255),
    "BDCUST" VARCHAR(255),
    "BDDIST" VARCHAR(255),
    "BDFLG3" VARCHAR(255),
    "BDFLG4" VARCHAR(255),
    "BDFRV" VARCHAR(255),
    PRIMARY KEY ("PODETAIL_ID") -- Generic PK (NEEDS VALIDATION!),
    FOREIGN KEY ("BDCUST") REFERENCES "ARCUST" ("CCUST") -- Inferred FK (Suffix: 'CUST'),
    FOREIGN KEY ("BDDIST") REFERENCES "GLMAST" ("GLMAST_ID") -- Inferred FK (Suffix: 'DIST')
);

-- Table: POHEADER
CREATE TABLE "POHEADER" (
    "BHCUD#" INT,
    "BHCUS#" VARCHAR(255),
    "BHDIST" VARCHAR(255),
    PRIMARY KEY ("BHCUD#"),
    FOREIGN KEY ("BHDIST") REFERENCES "GLMAST" ("GLMAST_ID") -- Inferred FK (Suffix: 'DIST')
);

-- Table: POHEADERBH
CREATE TABLE "POHEADERBH" (
    "BHCUD#" INT,
    "BHCUS#" VARCHAR(255),
    "BHDIST" VARCHAR(255),
    PRIMARY KEY ("BHCUD#"),
    FOREIGN KEY ("BHDIST") REFERENCES "GLMAST" ("GLMAST_ID") -- Inferred FK (Suffix: 'DIST')
);

-- Table: POSTPRD
CREATE TABLE "POSTPRD" (
    "POSTPRD_ID" INT,
    "PPDIST" VARCHAR(255),
    PRIMARY KEY ("POSTPRD_ID") -- Generic PK (NEEDS VALIDATION!),
    FOREIGN KEY ("PPDIST") REFERENCES "GLMAST" ("GLMAST_ID") -- Inferred FK (Suffix: 'DIST')
);

-- Table: POTRCK
CREATE TABLE "POTRCK" (
    "POTRCK_ID" INT,
    "PTCDIS" VARCHAR(255),
    "PTCUST" VARCHAR(255),
    "PTLINE" VARCHAR(255),
    PRIMARY KEY ("POTRCK_ID") -- Generic PK (NEEDS VALIDATION!),
    FOREIGN KEY ("PTCUST") REFERENCES "ARCUST" ("CCUST") -- Inferred FK (Suffix: 'CUST')
);

-- Table: POTRKHST
CREATE TABLE "POTRKHST" (
    "POTRKHST_ID" INT,
    "PTHCOM" VARCHAR(255),
    "PTHDST" VARCHAR(255),
    "PTHLIN" VARCHAR(255),
    PRIMARY KEY ("POTRKHST_ID") -- Generic PK (NEEDS VALIDATION!)
);

-- Table: PRCHCHRG
CREATE TABLE "PRCHCHRG" (
    "PRCHCHRG_ID" INT,
    "PJODST" VARCHAR(255),
    "PJORDR" VARCHAR(255),
    PRIMARY KEY ("PRCHCHRG_ID") -- Generic PK (NEEDS VALIDATION!),
    FOREIGN KEY ("PJORDR") REFERENCES "OEOPNORD" ("OOORDR") -- Inferred FK (Suffix: 'ORDR')
);

-- Table: PRCTCHRG
CREATE TABLE "PRCTCHRG" (
    "PRCTCHRG_ID" INT,
    "PKODST" VARCHAR(255),
    "PKORDR" VARCHAR(255),
    PRIMARY KEY ("PRCTCHRG_ID") -- Generic PK (NEEDS VALIDATION!),
    FOREIGN KEY ("PKORDR") REFERENCES "OEOPNORD" ("OOORDR") -- Inferred FK (Suffix: 'ORDR')
);

-- Table: PRCTDIM
CREATE TABLE "PRCTDIM" (
    "PRCTDIM_ID" INT,
    "PDITEM" VARCHAR(255),
    "PDODST" VARCHAR(255),
    "PDORDR" VARCHAR(255),
    PRIMARY KEY ("PRCTDIM_ID") -- Generic PK (NEEDS VALIDATION!),
    FOREIGN KEY ("PDORDR") REFERENCES "OEOPNORD" ("OOORDR") -- Inferred FK (Suffix: 'ORDR')
);

-- Table: RCPTCOST
CREATE TABLE "RCPTCOST" (
    "RCPTCOST_ID" INT,
    "ATBOL" VARCHAR(255),
    PRIMARY KEY ("RCPTCOST_ID") -- Generic PK (NEEDS VALIDATION!)
);

-- Table: RCPTHIST
CREATE TABLE "RCPTHIST" (
    "RCPTHIST_ID" INT,
    "RCBTCH" VARCHAR(255),
    "RCCTRY" VARCHAR(255),
    "RCTRAN" VARCHAR(255),
    PRIMARY KEY ("RCPTHIST_ID") -- Generic PK (NEEDS VALIDATION!)
);

-- Table: RESTOCK
CREATE TABLE "RESTOCK" (
    "RESTOCK_ID" INT,
    "RLULIN" VARCHAR(255),
    PRIMARY KEY ("RESTOCK_ID") -- Generic PK (NEEDS VALIDATION!)
);

-- Table: SADAILY
CREATE TABLE "SADAILY" (
    "SADAILY_ID" INT,
    "AYDIST" VARCHAR(255),
    "AYGPC" VARCHAR(255),
    "AYOGPC" VARCHAR(255),
    PRIMARY KEY ("SADAILY_ID") -- Generic PK (NEEDS VALIDATION!),
    FOREIGN KEY ("AYDIST") REFERENCES "GLMAST" ("GLMAST_ID") -- Inferred FK (Suffix: 'DIST')
);

-- Table: SAMTHLY
CREATE TABLE "SAMTHLY" (
    "SAMTHLY_ID" INT,
    "AMDIST" VARCHAR(255),
    "AMGDP1" VARCHAR(255),
    "AMGSP1" VARCHAR(255),
    PRIMARY KEY ("SAMTHLY_ID") -- Generic PK (NEEDS VALIDATION!),
    FOREIGN KEY ("AMDIST") REFERENCES "GLMAST" ("GLMAST_ID") -- Inferred FK (Suffix: 'DIST')
);

-- Table: SHIPADR
CREATE TABLE "SHIPADR" (
    "SHIPADR_ID" INT,
    "SAADR1" VARCHAR(255),
    "SAADR2" VARCHAR(255),
    "SAADR3" VARCHAR(255),
    "SACUST" VARCHAR(255),
    "SAFRTO" VARCHAR(255),
    "SAIDMX" VARCHAR(255),
    "SAINM" VARCHAR(255),
    "SAODMX" VARCHAR(255),
    "SAOUTM" TIMESTAMP,
    PRIMARY KEY ("SHIPADR_ID") -- Generic PK (NEEDS VALIDATION!),
    FOREIGN KEY ("SACUST") REFERENCES "ARCUST" ("CCUST") -- Inferred FK (Suffix: 'CUST')
);

-- Table: SHIPBCKG
CREATE TABLE "SHIPBCKG" (
    "SHIPBCKG_ID" INT,
    "SBCUST" VARCHAR(255),
    PRIMARY KEY ("SHIPBCKG_ID") -- Generic PK (NEEDS VALIDATION!),
    FOREIGN KEY ("SBCUST") REFERENCES "ARCUST" ("CCUST") -- Inferred FK (Suffix: 'CUST')
);

-- Table: SHIPDISP
CREATE TABLE "SHIPDISP" (
    "SHIPDISP_ID" INT,
    "SPCUST" VARCHAR(255),
    "SPDIST" VARCHAR(255),
    PRIMARY KEY ("SHIPDISP_ID") -- Generic PK (NEEDS VALIDATION!),
    FOREIGN KEY ("SPCUST") REFERENCES "ARCUST" ("CCUST") -- Inferred FK (Suffix: 'CUST'),
    FOREIGN KEY ("SPDIST") REFERENCES "GLMAST" ("GLMAST_ID") -- Inferred FK (Suffix: 'DIST')
);

-- Table: SHIPMAST
CREATE TABLE "SHIPMAST" (
    "SHIPMAST_ID" INT,
    "SHCORD" VARCHAR(255),
    "SHCUST" VARCHAR(255),
    "SHDIST" VARCHAR(255),
    "SHFISD" VARCHAR(255),
    "SHFISS" VARCHAR(255),
    "SHFSLD" VARCHAR(255),
    "SHFSLS" VARCHAR(255),
    "SHSHAP" VARCHAR(255),
    PRIMARY KEY ("SHIPMAST_ID") -- Generic PK (NEEDS VALIDATION!),
    FOREIGN KEY ("SHCUST") REFERENCES "ARCUST" ("CCUST") -- Inferred FK (Suffix: 'CUST'),
    FOREIGN KEY ("SHDIST") REFERENCES "GLMAST" ("GLMAST_ID") -- Inferred FK (Suffix: 'DIST')
);

-- Table: SHPINST
CREATE TABLE "SHPINST" (
    "SHPINST_ID" INT,
    "CICUST" VARCHAR(255),
    PRIMARY KEY ("SHPINST_ID") -- Generic PK (NEEDS VALIDATION!),
    FOREIGN KEY ("CICUST") REFERENCES "ARCUST" ("CCUST") -- Inferred FK (Suffix: 'CUST')
);

-- Table: SHSUMM
CREATE TABLE "SHSUMM" (
    "SHSUMM_ID" INT,
    "SUCUST" VARCHAR(255),
    "SUDIST" VARCHAR(255),
    "SUFISD" VARCHAR(255),
    "SUFISS" VARCHAR(255),
    PRIMARY KEY ("SHSUMM_ID") -- Generic PK (NEEDS VALIDATION!),
    FOREIGN KEY ("SUCUST") REFERENCES "ARCUST" ("CCUST") -- Inferred FK (Suffix: 'CUST'),
    FOREIGN KEY ("SUDIST") REFERENCES "GLMAST" ("GLMAST_ID") -- Inferred FK (Suffix: 'DIST')
);

-- Table: SLMNRCAP
CREATE TABLE "SLMNRCAP" (
    "SXGM" VARCHAR(255),
    "SXGP" VARCHAR(255),
    "SXGP#" INT,
    PRIMARY KEY ("SXGP#")
);

-- Table: SLMNSUM
CREATE TABLE "SLMNSUM" (
    "SLMNSUM_ID" INT,
    "SNFICS" VARCHAR(255),
    "SNFOCS" VARCHAR(255),
    PRIMARY KEY ("SLMNSUM_ID") -- Generic PK (NEEDS VALIDATION!)
);

-- Table: SLSASMT
CREATE TABLE "SLSASMT" (
    "SLSASMT_ID" INT,
    "MODIST" VARCHAR(255),
    PRIMARY KEY ("SLSASMT_ID") -- Generic PK (NEEDS VALIDATION!),
    FOREIGN KEY ("MODIST") REFERENCES "GLMAST" ("GLMAST_ID") -- Inferred FK (Suffix: 'DIST')
);

-- Table: SLSASYT
CREATE TABLE "SLSASYT" (
    "SLSASYT_ID" INT,
    "YODIST" VARCHAR(255),
    PRIMARY KEY ("SLSASYT_ID") -- Generic PK (NEEDS VALIDATION!),
    FOREIGN KEY ("YODIST") REFERENCES "GLMAST" ("GLMAST_ID") -- Inferred FK (Suffix: 'DIST')
);

-- Table: SLSDSCOV
CREATE TABLE "SLSDSCOV" (
    "SLSDSCOV_ID" INT,
    "DXTRNT" VARCHAR(255),
    "DXTYPE" VARCHAR(255),
    PRIMARY KEY ("SLSDSCOV_ID") -- Generic PK (NEEDS VALIDATION!)
);

-- Table: SPDETAIL
CREATE TABLE "SPDETAIL" (
    "SPDETAIL_ID" INT,
    "BTDIST" VARCHAR(255),
    PRIMARY KEY ("SPDETAIL_ID") -- Generic PK (NEEDS VALIDATION!),
    FOREIGN KEY ("BTDIST") REFERENCES "GLMAST" ("GLMAST_ID") -- Inferred FK (Suffix: 'DIST')
);

-- Table: SPHEADER
CREATE TABLE "SPHEADER" (
    "BSCUD#" INT,
    "BSCUS#" VARCHAR(255),
    "BSDIST" VARCHAR(255),
    "BSTRAK" VARCHAR(255),
    PRIMARY KEY ("BSCUD#"),
    FOREIGN KEY ("BSDIST") REFERENCES "GLMAST" ("GLMAST_ID") -- Inferred FK (Suffix: 'DIST')
);

-- Table: SPOTRCK
CREATE TABLE "SPOTRCK" (
    "SPOTRCK_ID" INT,
    "SPHCOM" VARCHAR(255),
    "SPORDR" VARCHAR(255),
    PRIMARY KEY ("SPOTRCK_ID") -- Generic PK (NEEDS VALIDATION!),
    FOREIGN KEY ("SPORDR") REFERENCES "OEOPNORD" ("OOORDR") -- Inferred FK (Suffix: 'ORDR')
);

-- Table: VENDSHIP
CREATE TABLE "VENDSHIP" (
    "VENDSHIP_ID" INT,
    "VSFRTO" VARCHAR(255),
    PRIMARY KEY ("VENDSHIP_ID") -- Generic PK (NEEDS VALIDATION!)
);

-- Table: VNDREQHD
CREATE TABLE "VNDREQHD" (
    "VNDREQHD_ID" INT,
    "V10SMO" VARCHAR(255),
    PRIMARY KEY ("VNDREQHD_ID") -- Generic PK (NEEDS VALIDATION!)
);

-- Table: WFOE895
CREATE TABLE "WFOE895" (
    "WFOE895_ID" INT,
    "DLGMCS" VARCHAR(255),
    "DLGMPC" VARCHAR(255),
    PRIMARY KEY ("WFOE895_ID") -- Generic PK (NEEDS VALIDATION!)
);

-- Table: _POHSTDET
CREATE TABLE "_POHSTDET" (
    "_POHSTDET_ID" INT,
    "BDBOL" VARCHAR(255),
    "BDCSMO" VARCHAR(255),
    "BDFRV" VARCHAR(255),
    PRIMARY KEY ("_POHSTDET_ID") -- Generic PK (NEEDS VALIDATION!)
);