--Identify PK on MW4FILE

SELECT 
    TABLE_SCHEMA, 
    TABLE_NAME, 
    COLUMN_NAME, 
    ORDINAL_POSITION AS KEY_SEQ,
    CONSTRAINT_NAME
FROM QSYS2.SYSKEYCST 
--WHERE TABLE_SCHEMA = 'MW4FILE'
ORDER BY TABLE_NAME, ORDINAL_POSITION;

SELECT 
    TABLE_SCHEMA
    --ORDINAL_POSITION AS KEY_SEQ
FROM QSYS2.SYSKEYCST 
--WHERE TABLE_SCHEMA = 'MW4FILE'
ORDER BY TABLE_NAME--, ORDINAL_POSITION;




-- Check SQL-defined PKs in MW4FILE
SELECT 
  TABLE_NAME, COLUMN_NAME, ORDINAL_POSITION, CONSTRAINT_NAME
FROM QSYS2.SYSKEYCST 
WHERE 
  TABLE_SCHEMA = 'MW4FILE' 
  AND CONSTRAINT_TYPE = 'PRIMARY KEY'
ORDER BY TABLE_NAME, ORDINAL_POSITION;
/*
 * SQL Error [42703]: [SQL0206] Column or global variable CONSTRAINT_TYPE not found.
 * */

-- Check DDS-defined keys (non-SQL constraints)
SELECT 
  TABLE_NAME, COLUMN_NAME, ORDINAL_POSITION 
FROM QSYS2.SYSKEYS 
WHERE 
  TABLE_SCHEMA = 'MW4FILE' 
  AND TABLE_NAME = 'SHIPMAST'
ORDER BY ORDINAL_POSITION;
/*
 SQL Error [42703]: [SQL0206] Column or global variable TABLE_NAME not found. 
 */ 

-- Find all FKs in MW4FILE
SELECT 
  CONSTRAINT_NAME, TABLE_NAME, COLUMN_NAME,
  REFERENCED_TABLE_SCHEMA, REFERENCED_TABLE_NAME, REFERENCED_COLUMN_NAME
FROM QSYS2.SYSKEYCST 
WHERE 
  TABLE_SCHEMA = 'MW4FILE' 
  AND CONSTRAINT_TYPE = 'FOREIGN KEY';
/*
 * SQL Error [42703]: [SQL0206] Column or global variable REFERENCED_COLUMN_NAME not found.
 */

-- Find FKs referencing SHIPMAST.SHORDN
SELECT 
  CONSTRAINT_NAME, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME,
  REFERENCED_TABLE_SCHEMA, REFERENCED_TABLE_NAME, REFERENCED_COLUMN_NAME
FROM QSYS2.SYSKEYCST 
WHERE 
  REFERENCED_TABLE_SCHEMA = 'MW4FILE' 
  AND REFERENCED_TABLE_NAME = 'SHIPMAST' 
  AND REFERENCED_COLUMN_NAME = 'SHORDN';
/*
 * SQL Error [42703]: [SQL0206] Column or global variable REFERENCED_COLUMN_NAME not found.
 * */


-- Detailed FK relationships
SELECT 
  c.CONSTRAINT_NAME, c.TABLE_SCHEMA, c.TABLE_NAME, 
  col.COLUMN_NAME, dep.REFERENCED_TABLE_SCHEMA, dep.REFERENCED_TABLE_NAME
FROM 
  QSYS2.SYSCST c
  JOIN QSYS2.SYSCSTCOL col ON c.CONSTRAINT_NAME = col.CONSTRAINT_NAME
  JOIN QSYS2.SYSCSTDEP dep ON c.CONSTRAINT_NAME = dep.CONSTRAINT_NAME
WHERE 
  c.CONSTRAINT_TYPE = 'FOREIGN KEY' 
  AND dep.REFERENCED_TABLE_NAME = 'SHIPMAST';

/*
 * SQL Error [42703]: [SQL0205] Column REFERENCED_TABLE_NAME not in table SYSCSTDEP in QSYS2.
*/

SELECT 
  CONSTRAINT_NAME, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME,
  REFERENCED_TABLE_SCHEMA, REFERENCED_TABLE_NAME, REFERENCED_COLUMN_NAME
FROM QSYS2.SYSKEYCST 
WHERE 
  REFERENCED_TABLE_SCHEMA = 'MW4FILE' 
  AND REFERENCED_TABLE_NAME = 'SHIPMAST' 
  AND REFERENCED_COLUMN_NAME = 'SHORDN';

/*
 * SQL Error [42703]: [SQL0206] Column or global variable REFERENCED_COLUMN_NAME not found.
 * */


/***********************************************************************************************************
 * *
 * *
 * *
 * *
 * *
 * CLAUDE
 * *
 * *
 * *
 * *
 * *
 * ********************************************************************************************************/
-- Method 1: Check SYSCST system table for constraints
SELECT 
    CONSTRAINT_SCHEMA, 
    CONSTRAINT_NAME,
    TABLE_SCHEMA,
    TABLE_NAME,
    CONSTRAINT_TYPE
FROM QSYS2.SYSCST
WHERE TABLE_SCHEMA = 'MW4FILE'
AND CONSTRAINT_TYPE = 'PRIMARY KEY'
ORDER BY TABLE_NAME;
/*
 * Empty results
 */


-- Method 2: Check SYSKEYS for unique keys (often used as PKs)
SELECT 
    K.TABLE_SCHEMA, 
    K.TABLE_NAME, 
    K.COLUMN_NAME, 
    K.ORDINAL_POSITION
FROM QSYS2.SYSKEYS K
JOIN QSYS2.SYSINDEXES I ON 
    K.TABLE_SCHEMA = I.TABLE_SCHEMA AND 
    K.INDEX_NAME = I.INDEX_NAME
WHERE K.TABLE_SCHEMA = 'MW4FILE'
AND I.IS_UNIQUE = 'YES'
ORDER BY K.TABLE_NAME, K.ORDINAL_POSITION;
/*
 * SQL Error [42703]: [SQL0205] Column TABLE_NAME not in table SYSKEYS in QSYS2.
*/




-- Method 1: Check REFERENTIAL_CONSTRAINTS view
SELECT 
    CONSTRAINT_SCHEMA,
    CONSTRAINT_NAME,
    UNIQUE_CONSTRAINT_SCHEMA,
    UNIQUE_CONSTRAINT_NAME,
    MATCH_OPTION,
    UPDATE_RULE,
    DELETE_RULE
FROM QSYS2.REFERENTIAL_CONSTRAINTS
WHERE CONSTRAINT_SCHEMA = 'MW4FILE'
ORDER BY CONSTRAINT_NAME;
/*
 * empty results
 */


-- Method 2: Check for all constraints and join with key columns
SELECT 
    R.CONSTRAINT_SCHEMA,
    R.CONSTRAINT_NAME,
    R.TABLE_NAME AS PARENT_TABLE,
    R.UNIQUE_CONSTRAINT_SCHEMA,
    R.UNIQUE_CONSTRAINT_NAME,
    C.TABLE_NAME AS CHILD_TABLE,
    K.COLUMN_NAME,
    K.ORDINAL_POSITION
FROM QSYS2.REFERENTIAL_CONSTRAINTS R
JOIN QSYS2.SYSCST C ON 
    R.CONSTRAINT_SCHEMA = C.CONSTRAINT_SCHEMA AND
    R.CONSTRAINT_NAME = C.CONSTRAINT_NAME
JOIN QSYS2.SYSKEYCST K ON
    C.CONSTRAINT_SCHEMA = K.CONSTRAINT_SCHEMA AND
    C.CONSTRAINT_NAME = K.CONSTRAINT_NAME
WHERE R.CONSTRAINT_SCHEMA = 'MW4FILE' OR R.UNIQUE_CONSTRAINT_SCHEMA = 'MW4FILE'
ORDER BY C.TABLE_NAME, K.ORDINAL_POSITION;
/*
 * SQL Error [42703]: [SQL0205] Column TABLE_NAME not in table REFERENTIAL_CONSTRAINTS in QSYS2.
 * */



-- Check available system catalog tables
SELECT 
    TABLE_NAME, 
    TABLE_TYPE
FROM QSYS2.SYSTABLES
WHERE TABLE_SCHEMA = 'QSYS2'
AND TABLE_NAME LIKE 'SYS%'
ORDER BY TABLE_NAME;
/*
 * SYSCATALOGS	V
SYSCHARSETS	T
SYSCHKCST	V
SYSCOLAUTH	V
SYSCOLUMNS	V
SYSCOLUMNSTAT	V
SYSCOLUMNS2	V
SYSCOLUMNS2_SESSION	V
SYSCONTROLS	V
SYSCONTROLSDEP	V
SYSCST	V
SYSCSTCOL	V
SYSCSTDEP	V
SYSDISKSTAT	V
SYSFIELDS	V
SYSFILES	V
SYSFUNCS	V
SYSHISTORYTABLES	V
SYSINDEXES	V
SYSINDEXSTAT	V
SYSIXADV	T
SYSJARCONTENTS	T
SYSJAROBJECTS	T
SYSKEYCST	V
SYSKEYS	V
SYSLIMITS	V
SYSLIMITS_BASIC	V
SYSLIMPA_A	V
SYSLIMPA_B	V
SYSLIMPJ_A	V
SYSLIMPJ_B	V
SYSLIMPO_A	V
SYSLIMPO_B	V
SYSLIMPS_A	V
SYSLIMPS_B	V
SYSLIMTBL	T
SYSMQTSTAT	V
SYSPACKAGE	V
SYSPACKAGEAUTH	V
SYSPACKAGESTAT	V
SYSPACKAGESTMTSTAT	V
SYSPARMS	T
SYSPARTITIONDISK	V
SYSPARTITIONINDEXDISK	V
SYSPARTITIONINDEXES	V
SYSPARTITIONINDEXSTAT	V
SYSPARTITIONMQTS	V
SYSPARTITIONSTAT	V
SYSPERIODS	V
SYSPROCS	V
SYSPROGRAMSTAT	V
SYSPROGRAMSTMTSTAT	V
SYSREFCST	V
SYSROUTDEP	T
SYSROUTINEAUTH	V
SYSROUTINEDEP	V
SYSROUTINES	T
SYSROUTINES_PREV	V
SYSSCHEMAAUTH	V
SYSSCHEMAS	V
SYSSEQOBJECTS	T
SYSSEQUENCEAUTH	V
SYSSEQUENCES	V
SYSTABAUTH	V
SYSTABLEDEP	V
SYSTABLEINDEXSTAT	V
SYSTABLES	V
SYSTABLESTAT	V
SYSTEM_STATUS_INFO	V
SYSTEM_STATUS_INFO_BASIC	V
SYSTEM_VALUE_INFO	V
SYSTEXTCOLUMNS	T
SYSTEXTCONFIGURATION	T
SYSTEXTDEFAULTS	T
SYSTEXTINDEXES	T
SYSTEXTSERVERHISTORY	T
SYSTEXTSERVERS	T
SYSTMPSTG	V
SYSTRIGCOL	V
SYSTRIGDEP	V
SYSTRIGGERS	V
SYSTRIGUPD	V
SYSTXTLBLS	T
SYSTYPES	T
SYSUDTAUTH	V
SYSVARIABLEAUTH	V
SYSVARIABLEDEP	T
SYSVARIABLES	T
SYSVIEWDEP	V
SYSVIEWS	V
SYSXSROBJECTAUTH	V
*/

 */

-- Alternative method 1: Check SYSKEYS structure first
SELECT * 
FROM QSYS2.SYSCOLUMNS 
WHERE TABLE_SCHEMA = 'QSYS2' 
AND TABLE_NAME = 'SYSKEYS' 
ORDER BY ORDINAL_POSITION;

-- Alternative method 2: Check system indexes
SELECT 
    SYSTEM_TABLE_SCHEMA, 
    SYSTEM_TABLE_NAME, 
    COLUMN_NAME, 
    ORDINAL_POSITION
FROM QSYS2.SYSINDEXCOL
WHERE SYSTEM_TABLE_SCHEMA = 'MW4FILE'
ORDER BY SYSTEM_TABLE_NAME, ORDINAL_POSITION;
/*
 * SQL Error [42704]: [SQL0204] SYSINDEXCOL in QSYS2 type *FILE not found.
 */

-- Alternative method 3: Try SYSTABCONST for constraints
SELECT * 
FROM QSYS2.SYSTABCONST
WHERE TABLE_SCHEMA = 'MW4FILE'
AND CONSTRAINT_TYPE = 'PRIMARY KEY'
ORDER BY TABLE_NAME;
/*
SQL Error [42704]: [SQL0204] SYSTABCONST in QSYS2 type *FILE not found.
*/



-- Check the structure of SYSKEYS
SELECT * 
FROM QSYS2.SYSCOLUMNS 
WHERE TABLE_SCHEMA = 'QSYS2' 
AND TABLE_NAME = 'SYSKEYS' 
ORDER BY ORDINAL_POSITION;

/*
csv attached
*/

-- Check the structure of SYSCST (constraints)
SELECT * 
FROM QSYS2.SYSCOLUMNS 
WHERE TABLE_SCHEMA = 'QSYS2' 
AND TABLE_NAME = 'SYSCST' 
ORDER BY ORDINAL_POSITION;
/*
csv attached
*/



-- Check for primary key constraints using SYSCST
SELECT 
    CONSTRAINT_SCHEMA,
    CONSTRAINT_NAME,
    TABLE_SCHEMA,
    TABLE_NAME,
    CONSTRAINT_TYPE
FROM QSYS2.SYSCST
WHERE TABLE_SCHEMA = 'MW4FILE'
AND CONSTRAINT_TYPE = 'PRIMARY KEY'  -- or try 'P' if this doesn't work
ORDER BY TABLE_NAME;
/*
 * No results
 */


-- Look for indexes on SHIPMAST table through SYSKEYS join with SYSINDEXES
SELECT 
    K.INDEX_SCHEMA,
    K.INDEX_NAME,
    K.COLUMN_NAME,
    K.ORDINAL_POSITION,
    K.ORDERING
FROM QSYS2.SYSKEYS K
JOIN QSYS2.SYSINDEXES I ON 
    K.INDEX_SCHEMA = I.INDEX_SCHEMA AND
    K.INDEX_NAME = I.INDEX_NAME
WHERE I.SYSTEM_TABLE_SCHEMA = 'MW4FILE'
AND I.SYSTEM_TABLE_NAME = 'SHIPMAST'
ORDER BY K.INDEX_NAME, K.ORDINAL_POSITION;

/*
 * no results
 * */


-- Check for foreign key constraints
SELECT 
    CONSTRAINT_SCHEMA,
    CONSTRAINT_NAME,
    TABLE_SCHEMA,
    TABLE_NAME,
    CONSTRAINT_TYPE
FROM QSYS2.SYSCST
WHERE TABLE_SCHEMA = 'MW4FILE'
AND CONSTRAINT_TYPE = 'FOREIGN KEY'  -- or try 'F' if this doesn't work
ORDER BY TABLE_NAME;
/*
 * NO results
 * */

-- Check SYSREFCST for actual foreign key relationships
SELECT * 
FROM QSYS2.SYSREFCST
WHERE CONSTRAINT_SCHEMA = 'MW4FILE' 
   OR UNIQUE_CONSTRAINT_SCHEMA = 'MW4FILE'
ORDER BY CONSTRAINT_NAME;

/*
NO results
*/

-- First get details about SHORDN column to understand its type
SELECT 
    TABLE_SCHEMA, 
    TABLE_NAME, 
    COLUMN_NAME, 
    DATA_TYPE, 
    LENGTH, 
    NUMERIC_SCALE, 
    IS_NULLABLE
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'MW4FILE'
AND TABLE_NAME = 'SHIPMAST'
AND COLUMN_NAME = 'SHORDN';
/*
NO results
*/

-- Find columns with similar names across all tables
SELECT 
    TABLE_SCHEMA, 
    TABLE_NAME, 
    COLUMN_NAME, 
    DATA_TYPE, 
    LENGTH
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'MW4FILE'
AND (COLUMN_NAME LIKE '%SHORDN%' OR COLUMN_NAME LIKE '%ORD%')
ORDER BY TABLE_NAME, COLUMN_NAME;
/*
 * Found 1811 rows
 * many of the tables use a name and increase numbers, for example
 *  X12856O0, X12856O1, X12856O2, X12856O3, X12856O4, X12856O5, X12856O6
*/

-- Find tables related to orders or shipping
SELECT 
    TABLE_SCHEMA, 
    TABLE_NAME, 
    TABLE_TYPE
FROM QSYS2.SYSTABLES
WHERE TABLE_SCHEMA = 'MW4FILE'
AND (TABLE_NAME LIKE '%ORDER%' OR TABLE_NAME LIKE '%ORD%' OR TABLE_NAME LIKE '%SHIP%')
ORDER BY TABLE_NAME;
/*
136 ROWS RETURNED
CSV Attached
*/




-- Get detailed information about SHIPMAST.SHORDN
SELECT 
    TABLE_SCHEMA, 
    TABLE_NAME, 
    COLUMN_NAME, 
    DATA_TYPE, 
    LENGTH, 
    NUMERIC_SCALE, 
    IS_NULLABLE
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'MW4FILE'
AND TABLE_NAME = 'SHIPMAST'
AND COLUMN_NAME = 'SHORDN';
/*
NO results
*/

-- Find all tables with SHORDN column
SELECT 
    TABLE_SCHEMA, 
    TABLE_NAME, 
    DATA_TYPE, 
    LENGTH, 
    NUMERIC_SCALE
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'MW4FILE'
AND COLUMN_NAME = 'SHORDN'
ORDER BY TABLE_NAME;
/*
68 ROWS
csv attached
*/

-- Find order-related physical files
SELECT 
    TABLE_SCHEMA, 
    TABLE_NAME
FROM QSYS2.SYSTABLES
WHERE TABLE_SCHEMA = 'MW4FILE'
AND TABLE_TYPE = 'P'
AND (TABLE_NAME LIKE '%ORD%' OR TABLE_NAME = 'ORDMAN' OR TABLE_NAME = 'ORDSUM')
ORDER BY TABLE_NAME;

/*
 * 21 rows
 * CSV Attached
 */

-- First, get the type of SHORDN (replace DATA_TYPE and LENGTH with actual values)
SELECT 
    COLUMN_NAME,
    TABLE_NAME,
    DATA_TYPE,
    LENGTH
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'MW4FILE'
AND TABLE_NAME = 'SHIPMAST'
AND COLUMN_NAME = 'SHORDN';
/*
 * Data_type 	NUMERIC
 * Lenght:		6
 */

-- Then find columns with matching type and length
-- Replace DATA_TYPE_VALUE and LENGTH_VALUE with actual values from above
SELECT 
    TABLE_NAME, 
    COLUMN_NAME,
    DATA_TYPE,
    LENGTH
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'MW4FILE'
AND DATA_TYPE = 'NUMERIC'  -- Replace with actual type
AND LENGTH = 6  -- Replace with actual length
--AND TABLE_TYPE = 'P'  -- Physical files only. --TABLE_TYPE is not recognized
AND TABLE_NAME IN (
    SELECT TABLE_NAME
    FROM QSYS2.SYSTABLES
    WHERE TABLE_SCHEMA = 'MW4FILE'
    AND TABLE_TYPE = 'P'
    AND (TABLE_NAME LIKE '%ORD%' OR TABLE_NAME LIKE '%SHIP%')
)
ORDER BY TABLE_NAME, COLUMN_NAME;
/*
 /*tABLE_TYPE was not found. So I commented it to query all table types
 * 33 results
  CSV Attached
  */


-- Check ORDMAN - Order Management main table
-- Show all columns to understand structure
SELECT 
    COLUMN_NAME, 
    DATA_TYPE, 
    LENGTH
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'MW4FILE'
AND TABLE_NAME = 'ORDMAN'
ORDER BY ORDINAL_POSITION;

-- Check ORDSUM - Order Summary likely
SELECT 
    COLUMN_NAME, 
    DATA_TYPE, 
    LENGTH
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'MW4FILE'
AND TABLE_NAME = 'ORDSUM'
ORDER BY ORDINAL_POSITION;


-- See if SHORDN values exist in ORDMAN.ORDNUM
SELECT COUNT(*) AS match_count
FROM MW4FILE.SHIPMAST S
JOIN MW4FILE.ORDMAN O ON S.SHORDN = O.ORDNUM;

-- Compare with total count
SELECT COUNT(*) AS total_shipments
FROM MW4FILE.SHIPMAST;
