USE SigmaTB;

SELECT LTRIM(RTRIM(GLT.GLDESC)) AS GLDESC, GLA.GACDES, SUM(CASE WHEN GLCRDB = 'C' THEN +GLAMT WHEN GLCRDB = 'D' THEN -GLAMT ELSE 0 END) AS AdjustedAmount
            FROM GLTRANS GLT LEFT JOIN GLACCT GLA ON GLT.GLACCT = GLA.GACCT
            WHERE GLA.GARP3 IN (500, 530, 600, 610) AND GLT.[GLTRN#] = 0 AND GLT.GLPYY = 25 AND GLT.GLPMM = 2 AND LEN(LTRIM(RTRIM(GLT.GLDESC))) <> 6
            GROUP BY LTRIM(RTRIM(GLT.GLDESC)), GLA.GACDES;

SELECT 
    LTRIM(RTRIM(GLT.GLDESC)) AS GLDESC, 
    GLA.GACDES, 
    SUM(
        CASE 
            WHEN GLCRDB = 'C' THEN +GLAMT 
            WHEN GLCRDB = 'D' THEN -GLAMT 
            ELSE 0 
        END
    ) AS AdjustedAmount
FROM 
    GLTRANS GLT 
    LEFT JOIN GLACCT GLA 
        ON GLT.GLACCT = GLA.GACCT
WHERE 
    GLA.GARP3 IN (500, 530, 600, 610) 
    AND GLT.[GLTRN#] = 0 
    AND GLT.GLPYY = 25 
    AND GLT.GLPMM = 2 
    AND LEN(LTRIM(RTRIM(GLT.GLDESC))) <> 6
GROUP BY 
    LTRIM(RTRIM(GLT.GLDESC)), 
    GLA.GACDES;



--Example info

BEGIN
    USE SigmaTB;
    SELECT * 
    FROM [dbo].[z_General_Ledger_Transaction_File_____GLTRANS]
    WHERE 
        [Posting_Year_____GLPYY] = 25
        AND [Posting_Month_____GLPMM] = 2
END
