USE SigmaTB;
GO


--ROP - Base Price
    --ORIGINAL
    --set @myvarInputSQL = '''SELECT ''price'', [ITEMONHD].[IOITEM], [ITEMONHD].[IOBPRC] FROM [ITEMONHD] [ITEMONHD];'''
    --TRANSLATED
    --SELECT 'price', [mrs].[z_Item_on_Hand_File_____ITEMONHD].[ITEM_NUMBER_____IOITEM], [z_Item_on_Hand_File_____ITEMONHD].[Base_Price_____IOBPRC] FROM [mrs].[z_Item_on_Hand_File_____ITEMONHD];



-- ROP - Material Processing
            /*--Original
            set @myvarInputSQL = 'SELECT [MPDETAIL].[MDORDR], [APVEND].[VVNDR], [APVEND].[VALPHA], [MPDETAIL].[MDCLOS], [MPDETAIL].[MDITEM], 
                    [MPDETAIL].[MDCRTD], [MPDETAIL].[MDRQCC]*1000000+[MPDETAIL].[MDRQYY]*10000+[MPDETAIL].[MDRQMM]*100+[MPDETAIL].[MDRQDD], [MPDETAIL].[MDOQTY], 
                    [MPDETAIL].[MDOUOM], [MPDETAIL].[MDIQTY] 
            FROM    [APVEND] [APVEND], [MPDETAIL] [MPDETAIL] 
            WHERE   [APVEND].[VCOMP] = [MPDETAIL].[MDCOMP] AND [APVEND].[VVNDR] = [MPDETAIL].[MDVNDR] ORDER BY [MPDETAIL].[MDITEM], [MPDETAIL].[MDORDR] DESC;'
            */

--ROP - PRICE -- PO query
        /*
            --Original
            set @myvarInputSQL = '''SELECT ''Purchase order'', [PODETAIL].[BDPONO], [PODETAIL].[BDVNDR], [APVEND].[VNAME], [PODETAIL].[BDRECD], [PODETAIL].[BDITEM], [PODETAIL].[BDCRTD], [PODETAIL].[bdrpcc]*1000000+[PODETAIL].[bdrpyy]*10000+[PODETAIL].[bdrpmm]*100+[PODETAIL].[bdrpdd], [PODETAIL].[BDOQOO], [PODETAIL].[BDIUOM], [PODETAIL].[BDCQOO], [PODETAIL].[BDOOQ], [PODETAIL].[BDTIQR], [PODETAIL].[bdpocc]*1000000+[PODETAIL].[bdpoyy]*10000+[PODETAIL].[bdpomm]*100+[PODETAIL].[bdpodd], [PODETAIL].[bdrccc]*1000000+[PODETAIL].[bdrcyy]*10000+[PODETAIL].[bdrcmm]*100+[PODETAIL].[bdrcdd]
            FROM [PODETAIL] LEFT OUTER JOIN [APVEND] ON [PODETAIL].[BDVNDR] = [APVEND].[VVNDR]
            WHERE ([PODETAIL].[BDITEM] Between ''50000'' And ''99998'')
            ORDER BY [PODETAIL].[BDITEM], [PODETAIL].[BDPONO] DESC'''


*/



--ROP - QUERY -- ROP QUERY
/*
        --Original
        set @myvarInputSQL = '''SELECT ''ROP Query'', [ITEMMAST].[IMFSP2], [ITEMMAST].[IMITEM], [ITEMMAST].[IMSIZ1], [ITEMMAST].[IMSIZ2], [ITEMMAST].[IMSIZ3], [ITEMMAST].[IMDSC2], [ITEMMAST].[IMWPFT], [ITEMONHD].[IOACST], [ITEMONHD].[IOQOH], [ITEMONHD].[IOQOO], [ITEMONHD].[IOQOR]+[ITEMONHD].[IOQOOR], [ITEMMAST].[IMDSC1], [ITEMMAST].[IMWUOM], [ITEMMAST].[IMCSMO]
        FROM [ITEMMAST] [ITEMMAST], [ITEMONHD] [ITEMONHD]
        WHERE [ITEMONHD].[IOITEM] = [ITEMMAST].[IMITEM] AND (([ITEMMAST].[IMRECD]=''A'') AND ([ITEMMAST].[IMITEM] Between ''49999'' And ''90000''))
        ORDER BY [ITEMMAST].[IMFSP2]'''

*/

--ROP_query_
--Sales Data	
            /*
            --Original
            set @myvarInputSQL = '''SELECT ''Sales data'', [OEOPNORD].[OORECD], [OEDETAIL].[ODTYPE], [OEDETAIL].[ODITEM], [OEDETAIL].[ODORDR], [OEOPNORD].[OOCUST], [ARCUST].[CALPHA], [OEDETAIL].[ODTLBS], [OEDETAIL].[ODTFTS], [OEOPNORD].[OOOCC]*1000000 + [OEOPNORD].[OOOYY]*10000 + [OEOPNORD].[OOOMM]*100 + [OEOPNORD].[OOODD], [ARCUST].[CSMDI1]*100 + [ARCUST].[CSLMN1]  
                    FROM [ARCUST] [ARCUST], [OEDETAIL] [OEDETAIL], [OEOPNORD] [OEOPNORD]  
                    WHERE [OEDETAIL].[ODORDR] = [OEOPNORD].[OOORDR] AND [OEOPNORD].[OOCUST] = [ARCUST].[CCUST] AND ([OEOPNORD].[OORECD] = ''A'' AND [OEDETAIL].[ODTYPE] IN (''A'', ''C''))  
                    ORDER BY [OEDETAIL].[ODITEM];'''


--ROP_query_


--Tag Query	
        /*
        --Original
        set @myvarInputSQL = '''SELECT ''TAG query'', [ITEMTAG].[ITITEM], [ITEMTAG].[ITTAG], [ITEMTAG].[ITTDES], [ITEMTAG].[ITLNTH], [ITEMTAG].[ITTPCS], [ITEMTAG].[ITHEAT], [ITEMTAG].[ITV301], [ITEMTAG].[ITLOCT], [ITEMTAG].[ITTQTY], [ITEMTAG].[ITRQTY], [ITEMMAST].[IMFSP2]  
                FROM [ITEMMAST] [ITEMMAST], [ITEMTAG] [ITEMTAG]  
                WHERE [ITEMTAG].[ITITEM] = [ITEMMAST].[IMITEM] AND ([ITEMTAG].[ITRECD] = ''A'' AND [ITEMTAG].[ITITEM] > ''49999'')  
                ORDER BY [ITEMTAG].[ITITEM], [ITEMTAG].[ITHEAT], [ITEMTAG].[ITV301], [ITEMTAG].[ITLNTH];'''



-- ROP_query_
-- Usage Query	
-- This query retrieves historical item usage data based on transaction dates and item ranges.
-- This query has a PARAMETER in which ask the date.. for query purposes I set january 1st 2025
/*
        -- Original
        set @myvarInputSQL = '''SELECT ''Usage query'', [ITEMHIST].[IHITEM], [ITEMHIST].[IHTRNT], [ITEMHIST].[IHTRN#], [ITEMHIST].[IHVNDR], [ITEMHIST].[IHCUST], [ITEMHIST].[IHTRYY], [ITEMHIST].[IHTRMM], [ITEMHIST].[IHTRDD], [ITEMHIST].[IHTQTY]  
                FROM [ITEMHIST] [ITEMHIST]  
                WHERE ([ITEMHIST].[IHTRCC]*1000000 + [ITEMHIST].[IHTRYY]*10000 + [ITEMHIST].[IHTRMM]*100 + [ITEMHIST].[IHTRDD] > ?) AND ([ITEMHIST].[IHITEM] BETWEEN ''50000'' AND ''99998'')  
                ORDER BY [ITEMHIST].[IHITEM], [ITEMHIST].[IHTRYY], [ITEMHIST].[IHTRMM], [ITEMHIST].[IHTRDD];'''

*/


-- ROP_query
-- Usage sum query
-- This query calculates the sum of usage for items within a specific range and date.	
/*
        -- Original
            set @myvarInputSQL = '''SELECT ''ROP - Usage sum query'', DISTINCT [ITEMHIST].[IHITEM], [ITEMHIST].[IHTRNT], [ITEMHIST].[IHCUST], [ARCUST].[CALPHA], [ARCUST].[CSMDI1]*100 + [ARCUST].[CSLMN1]  
                    FROM [ARCUST] [ARCUST], [ITEMHIST] [ITEMHIST]  
                    WHERE [ARCUST].[CCUST] = [ITEMHIST].[IHCUST] AND ([ITEMHIST].[IHTRCC]*1000000 + [ITEMHIST].[IHTRYY]*10000 + [ITEMHIST].[IHTRMM]*100 + [ITEMHIST].[IHTRDD] > ? AND [ITEMHIST].[IHITEM] BETWEEN ''50000'' AND ''99998'' AND [ITEMHIST].[IHTRNT] IN (''CR'', ''IN''))  
                    ORDER BY [ITEMHIST].[IHITEM], [ARCUST].[CALPHA];'''

*/


--SalesAnalisysQuery_
--CreditMemos	
            --     
            /*     
            -- Original
            --set @myvarInputSQL = '''SELECT ''credit memos'', [OEDETAIL].[ODDIST]*1000000 + [OEDETAIL].[ODORDR], [SALESMAN].[SMNAME], [OEOPNORD].[OOTYPE], [OEDETAIL].[ODCDIS]*100000 + [OEDETAIL].[ODCUST], [ARCUST].[CALPHA], [OEDETAIL].[ODITEM], [OEDETAIL].[ODSIZ1], [OEDETAIL].[ODSIZ2], [OEDETAIL].[ODSIZ3], [OEDETAIL].[ODCRTD], [OEDETAIL].[ODTFTS], [OEDETAIL].[ODTLBS], [OEDETAIL].[ODTPCS], [OEDETAIL].[ODSLSX], [OEDETAIL].[ODFRTS], [OEDETAIL].[ODCSTX], [OEDETAIL].[ODPRCC], [OEDETAIL].[ODADCC], [OEDETAIL].[ODWCCS], [ARCUST].[CSTAT], [ARCUST].[CCTRY], [OEOPNORD].[OOICC]*1000000 + [OEOPNORD].[OOIYY]*10000 + [OEOPNORD].[OOIMM]*100 + [OEOPNORD].[OOIDD], [OEDETAIL].[ODCREF]  
            --        FROM [ARCUST] [ARCUST], [OEDETAIL] [OEDETAIL], [OEOPNORD] [OEOPNORD], [SALESMAN] [SALESMAN]  
            --       WHERE [OEDETAIL].[ODDIST] = [OEOPNORD].[OODIST] AND [OEDETAIL].[ODORDR] = [OEOPNORD].[OOORDR] AND [OEOPNORD].[OOCDIS] = [ARCUST].[CDIST] AND [OEOPNORD].[OOCUST] = [ARCUST].[CCUST] AND [OEOPNORD].[OOISMD] = [SALESMAN].[SMDIST] AND [OEOPNORD].[OOISMN] = [SALESMAN].[SMSMAN] AND ([OEOPNORD].[OOTYPE] = ''C'' AND [OEOPNORD].[OORECD] = ''W'' AND ([OEOPNORD].[OOICC]*10000 + [OEOPNORD].[OOIYY]*100 + [OEOPNORD].[OOIMM] BETWEEN 20250101 AND ?));'''

*/



--SalesAnalisysQuery_
--Customer-Summary	
        /*
        -- Original
        set @myvarInputSQL = '''SELECT DISTINCT ''customer summary'',  [ARCUST].[CDIST]*100000 + [ARCUST].[CCUST] as CDIST_CCUST, [ARCUST].[CALPHA], [ARCUST].[CLIMIT], [ARCUST].[CISMD1]*100 + [ARCUST].[CISLM1], [ARCUST].[CSMDI1]*100 + [ARCUST].[CSLMN1], [SALESMAN].[SMNAME]  
            FROM [ARCUST] [ARCUST], [SALESMAN] [SALESMAN]  
            WHERE [ARCUST].[CISMD1] = [SALESMAN].[SMDIST] AND [ARCUST].[CISLM1] = [SALESMAN].[SMSMAN]  
            ORDER BY [ARCUST].[CALPHA];'''


        */


--SalesAnalisysQuery_
--Customer-Summary1	
        /*
            --Original
            set @myvarInputSQL = '''SELECT DISTINCT ''Sales analysis Customer summary'', [SALESMAN].[SMDIST]*100 + [SALESMAN].[SMSMAN], [SALESMAN].[SMNAME]
                    FROM [SALESMAN] [SALESMAN];'''

        */


--SalesAnalisysQuery_
--QueryFromMetalNet1	
            
                -- Original
                -- its all the ITEMONHD
 /*           set @myvarInputSQL = '''SELECT ''Sales analysis, query'', [ITEMONHD].[IORECD], [ITEMONHD].[IOCOMP], [ITEMONHD].[IODIST], [ITEMONHD].[IOITEM],
                [ITEMONHD].[IOQOH], [ITEMONHD].[IOQOR], [ITEMONHD].[IOQOO], [ITEMONHD].[IOQOOR], [ITEMONHD].[IOQIT], [ITEMONHD].[IOQHLD], [ITEMONHD].[IOQCOL], 
                [ITEMONHD].[IOROH], [ITEMONHD].[IOROR], [ITEMONHD].[IOROO], [ITEMONHD].[IOROOR], [ITEMONHD].[IORIT], [ITEMONHD].[IORIQC], [ITEMONHD].[IOBOMI], 
                [ITEMONHD].[IOBOMC], [ITEMONHD].[IOLCCC], [ITEMONHD].[IOLCYY], [ITEMONHD].[IOLCMM], [ITEMONHD].[IOLCDD], [ITEMONHD].[IOCUOM], [ITEMONHD].[IOACST], 
                [ITEMONHD].[IORCST], [ITEMONHD].[IORLCK], [ITEMONHD].[IOFCST], [ITEMONHD].[IOSCST], [ITEMONHD].[IOSCCC], [ITEMONHD].[IOSCYY], [ITEMONHD].[IOSCMM], 
                [ITEMONHD].[IOSCDD], [ITEMONHD].[IODOSC], [ITEMONHD].[IODOSL], [ITEMONHD].[IOMNRQ], [ITEMONHD].[IOTORQ], [ITEMONHD].[IOPYIB], [ITEMONHD].[IOCYIB], 
                [ITEMONHD].[IOCYIU], [ITEMONHD].[IOITST], [ITEMONHD].[IOPLVL], [ITEMONHD].[IOBGIN], [ITEMONHD].[IOMNBL], [ITEMONHD].[IOROPT], [ITEMONHD].[IOROPL], 
                [ITEMONHD].[IOROQT], [ITEMONHD].[IOLDTM], [ITEMONHD].[IOBUY], [ITEMONHD].[IOBGIT], [ITEMONHD].[IOROFC], [ITEMONHD].[IOSSTK], [ITEMONHD].[IOLDTL], 
                [ITEMONHD].[IOINVC], [ITEMONHD].[IOMTST], [ITEMONHD].[IODISC], [ITEMONHD].[IOOWNF], [ITEMONHD].[IONSDC], [ITEMONHD].[IO1RCT], [ITEMONHD].[IOTOPP], 
                [ITEMONHD].[IOPMON], [ITEMONHD].[IOLOCC], [ITEMONHD].[IOLOYY], [ITEMONHD].[IOLOMM], [ITEMONHD].[IOLODD], [ITEMONHD].[IO1ACQ], [ITEMONHD].[IOLFB1], 
                [ITEMONHD].[IOLFB2], [ITEMONHD].[IOCMNT], [ITEMONHD].[IOMSLS], [ITEMONHD].[IOYSLS], [ITEMONHD].[IOMCST], [ITEMONHD].[IOYCST], [ITEMONHD].[IOMUNT], 
                [ITEMONHD].[IOYUNT], [ITEMONHD].[IOMWGT], [ITEMONHD].[IOYWGT], [ITEMONHD].[IODLCC], [ITEMONHD].[IODLYY], [ITEMONHD].[IODLMM], [ITEMONHD].[IODLDD], 
                [ITEMONHD].[IOPUOM], [ITEMONHD].[IOCNTP], [ITEMONHD].[IOCNTL], [ITEMONHD].[IOBPRC], [ITEMONHD].[IOBPRL], [ITEMONHD].[IOBPCC], [ITEMONHD].[IOBPYY], 
                [ITEMONHD].[IOBPMM], [ITEMONHD].[IOBPDD], [ITEMONHD].[IOCNTC], [ITEMONHD].[IOCDIS], [ITEMONHD].[IOCUST], [ITEMONHD].[IOMACN], [ITEMONHD].[IOPRCD], 
                [ITEMONHD].[IORUNR], [ITEMONHD].[IORUOM], [ITEMONHD].[IOMEIF], [ITEMONHD].[IOORDI], [ITEMONHD].[IOMDIF], [ITEMONHD].[IOPMCC], [ITEMONHD].[IOPMYY], 
                [ITEMONHD].[IOPMMM], [ITEMONHD].[IOPMDD], [ITEMONHD].[IOPMCD], [ITEMONHD].[IOLRCS], [ITEMONHD].[IOZ], [ITEMONHD].[IOC], [ITEMONHD].[IOD], [ITEMONHD].
                [IOPCTF], [ITEMONHD].[IOOUOM], [ITEMONHD].[IOMAGA], [ITEMONHD].[IOHURD], [ITEMONHD].[IOATAJ], [ITEMONHD].[IOLPCC], [ITEMONHD].[IOLPYY], [ITEMONHD].[IOLPMM], 
                [ITEMONHD].[IOLPDD], [ITEMONHD].[IOLPUS], [ITEMONHD].[IOLSCC], [ITEMONHD].[IOLSYY], [ITEMONHD].[IOLSMM], [ITEMONHD].[IOLSDD], [ITEMONHD].[IOLSUS], 
                [ITEMONHD].[IOLMCC], [ITEMONHD].[IOLMYY], [ITEMONHD].[IOLMMM], [ITEMONHD].[IOLMDD], [ITEMONHD].[IOLMUS], [ITEMONHD].[IOCLS3], [ITEMONHD].[IOSBCL], 
                [ITEMONHD].[IOSTCL], [ITEMONHD].[IOPUSD], [ITEMONHD].[IOPUSQ], [ITEMONHD].[IOPCST], [ITEMONHD].[IOPSLS], [ITEMONHD].[IOPUNT], [ITEMONHD].[IOPLBS], 
                [ITEMONHD].[IOPATN], [ITEMONHD].[IOMOST], [ITEMONHD].[IOBOMW], [ITEMONHD].[IOAVMS], [ITEMONHD].[IOAVLB], [ITEMONHD].[IOAVOH], [ITEMONHD].[IOAVOS], 
                [ITEMONHD].[IOUSQT], [ITEMONHD].[IOUSDL], [ITEMONHD].[IOYTDL], [ITEMONHD].[IOLIFO], [ITEMONHD].[IOSRCE], [ITEMONHD].[IOSUCC], [ITEMONHD].[IOSUYY], 
                [ITEMONHD].[IOSUMM], [ITEMONHD].[IOSUDD], [ITEMONHD].[IOOPPO], [ITEMONHD].[IOOPPD], [ITEMONHD].[IOTSTR], [ITEMONHD].[IOAVMQ], [ITEMONHD].[IOITDL], 
                [ITEMONHD].[IOITUN], [ITEMONHD].[IORSTK], [ITEMONHD].[IORSMP], [ITEMONHD].[IOHFRR], [ITEMONHD].[IOCORS], [ITEMONHD].[IOTRRS], [ITEMONHD].[IOMPRS], 
                [ITEMONHD].[IOSTOR], [ITEMONHD].[IOASOR], [ITEMONHD].[IOAVG3], [ITEMONHD].[IOAV12], [ITEMONHD].[IOPICC], [ITEMONHD].[IOPIYY], [ITEMONHD].[IOPIMM], 
                [ITEMONHD].[IOPIDD], [ITEMONHD].[IOPDSC], [ITEMONHD].[IOITRM], [ITEMONHD].[IOLPMC], [ITEMONHD].[IOLPML], [ITEMONHD].[IOCPMC], [ITEMONHD].[IOCPML], 
                [ITEMONHD].[IODSPS], [ITEMONHD].[IOSPCD], [ITEMONHD].[IOPRC2], [ITEMONHD].[IOSALE], [ITEMONHD].[IOQQTY], [ITEMONHD].[IOQAC], [ITEMONHD].[IOOELK], 
                [ITEMONHD].[IOMPLK], [ITEMONHD].[IOABCP], [ITEMONHD].[IOANRS], [ITEMONHD].[IOTAX], [ITEMONHD].[IORBCS], [ITEMONHD].[IOTUNA]  
                    FROM [ITEMONHD] [ITEMONHD];'''

/*            
            -- WORKING
            SELECT * FROM ITEMONHD

*/


--SalesAnalisysQuery
--SalesOrders	xxxx
/*
                
                -- Original

                --SELECT CAST([OEDETAIL].[oddist] AS INT) * 1000000 + CAST([OEDETAIL].[odordr] AS INT), [SALESMAN].[SMNAME], [OEOPNORD].[OOTYPE], CAST([OEDETAIL].[odcdis] AS INT) * 100000 + CAST([OEDETAIL].[odcust] AS INT), [ARCUST].[CALPHA], CAST([OEOPNORD].[OOICC] AS INT) * 1000000 + CAST([OEOPNORD].[OOIYY] AS INT) * 10000 + CAST([OEOPNORD].[OOIMM] AS INT) * 100 + CAST([OEOPNORD].[OOIDD] AS INT), [OEDETAIL].[ODITEM], [OEDETAIL].[ODSIZ1], [OEDETAIL].[ODSIZ2], [OEDETAIL].[ODSIZ3], [OEDETAIL].[ODCRTD], [SLSDSCOV].[DXDSC2], [OEDETAIL].[ODTFTS], [OEDETAIL].[ODTLBS], [OEDETAIL].[ODTPCS], [OEDETAIL].[ODSLSX], [OEDETAIL].[ODFRTS], [OEDETAIL].[ODCSTX], [OEDETAIL].[ODPRCC], [OEDETAIL].[ODADCC], [OEDETAIL].[ODWCCS], [ARCUST].[CSTAT], [ARCUST].[CCTRY]
                --FROM [mrs].[ARCUST] AS [ARCUST], [mrs].[OEDETAIL] AS [OEDETAIL], [mrs].[OEOPNORD] AS [OEOPNORD], [mrs].[SALESMAN] AS [SALESMAN], [mrs].[SLSDSCOV] AS [SLSDSCOV]
                --WHERE CAST([OEDETAIL].[ODDIST] AS INT) = CAST([OEOPNORD].[OODIST] AS INT) AND CAST([OEDETAIL].[ODDIST] AS INT) = CAST([SLSDSCOV].[DXDIST] AS INT) AND CAST([OEDETAIL].[ODMLIN] AS INT) = CAST([SLSDSCOV].[DXMLIN] AS INT) AND CAST([OEDETAIL].[ODORDR] AS INT) = CAST([OEOPNORD].[OOORDR] AS INT) AND CAST([OEDETAIL].[ODORDR] AS INT) = CAST([SLSDSCOV].[DXORDR] AS INT) AND CAST([OEOPNORD].[OOCDIS] AS INT) = CAST([ARCUST].[CDIST] AS INT) AND CAST([OEOPNORD].[OOCUST] AS INT) = CAST([ARCUST].[CCUST] AS INT) AND CAST([OEOPNORD].[OOISMD] AS INT) = CAST([SALESMAN].[SMDIST] AS INT) AND CAST([OEOPNORD].[OOISMN] AS INT) = CAST([SALESMAN].[SMSMAN] AS INT) AND (([OEOPNORD].[OOTYPE] IN ('A','B')) AND ([OEOPNORD].[OORECD]='W') AND (CAST([OEOPNORD].[ooicc] AS INT)*10000+CAST([OEOPNORD].[ooiyy] AS INT)*100+CAST([OEOPNORD].[ooimm] AS INT) BETWEEN @StartDate AND @EndDate))


*/





--SalesAnalisysQuery_
--SPO
        /*
        --Original
                --set @myvarInputSQL = '''SELECT ''Sales analysis, SPO'', [OEDETAIL].[ODDIST]*1000000 + [OEDETAIL].[ODORDR], [SALESMAN].[SMNAME], [OEOPNORD].[OOTYPE], [OEDETAIL].[ODCDIS]*100000 + [OEDETAIL].[ODCUST], [ARCUST].[CALPHA], [OEOPNORD].[OOICC]*100 + [OEOPNORD].[OOIYY], [OEOPNORD].[OOIMM], [OEOPNORD].[OOIDD], [OEDETAIL].[ODITEM], [SPHEADER].[BSSVEN], [SPHEADER].[BSSPS#]
                --FROM [ARCUST] [ARCUST], [OEDETAIL] [OEDETAIL], [OEOPNORD] [OEOPNORD], [SALESMAN] [SALESMAN], [SPHEADER] [SPHEADER]
                --WHERE [OEDETAIL].[ODDIST] = [OEOPNORD].[OODIST] AND [OEDETAIL].[ODORDR] = [OEOPNORD].[OOORDR] AND [OEOPNORD].[OOCDIS] = [ARCUST].[CDIST] AND [OEOPNORD].[OOCUST] = [ARCUST].[CCUST] AND [OEOPNORD].[OOISMD] = [SALESMAN].[SMDIST] AND [OEOPNORD].[OOISMN] = [SALESMAN].[SMSMAN] AND [OEDETAIL].[ODDIST] = [SPHEADER].[BSDIST] AND [OEDETAIL].[ODORDR] = [SPHEADER].[BSORDR] AND ([OEOPNORD].[OOTYPE] IN ('A','B') AND [OEOPNORD].[OORECD] = 'W' AND [OEDETAIL].[ODDIST] = 1 AND [OEDETAIL].[ODORDR] > ?);'''

                --SET @myvarInputSQL = 'SELECT ''Sales analysis, SPO'', [OEDETAIL].[ODDIST]*1000000 + [OEDETAIL].[ODORDR], [SALESMAN].[SMNAME], [OEOPNORD].[OOTYPE], [OEDETAIL].[ODCDIS]*100000 + [OEDETAIL].[ODCUST], [ARCUST].[CALPHA], [OEOPNORD].[OOICC]*100 + [OEOPNORD].[OOIYY], [OEOPNORD].[OOIMM], [OEOPNORD].[OOIDD], [OEDETAIL].[ODITEM], [SPHEADER].[BSSVEN], [SPHEADER].[BSSPS#] FROM [ARCUST] AS [ARCUST], [OEDETAIL] AS [OEDETAIL], [OEOPNORD] AS [OEOPNORD], [SALESMAN] AS [SALESMAN], [SPHEADER] AS [SPHEADER] WHERE [OEDETAIL].[ODDIST] = [OEOPNORD].[OODIST] AND [OEDETAIL].[ODORDR] = [OEOPNORD].[OOORDR] AND [OEOPNORD].[OOCDIS] = [ARCUST].[CDIST] AND [OEOPNORD].[OOCUST] = [ARCUST].[CCUST] AND [OEOPNORD].[OOISMD] = [SALESMAN].[SMDIST] AND [OEOPNORD].[OOISMN] = [SALESMAN].[SMSMAN] AND [OEDETAIL].[ODDIST] = [SPHEADER].[BSDIST] AND [OEDETAIL].[ODORDR] = [SPHEADER].[BSORDR] AND ([OEOPNORD].[OOTYPE] IN (''A'',''B'') AND [OEOPNORD].[OORECD] = ''W'' AND [OEDETAIL].[ODDIST] = 1 AND [OEDETAIL].[ODORDR] > ?);';

        */


;

--Shipmast_
--QueryfromMetalNet	
--set @myvarInputSQL = ''' SELECT ''Shipmaster'', [SHIPMAST].[SHRECD], [SHIPMAST].[SHCOMP], [SHIPMAST].[SHDIST], [SHIPMAST].[SHORDN], [SHIPMAST].[SHCORD], [SHIPMAST].[SHOREL], [SHIPMAST].[SHITEM], [SHIPMAST].[SHMDIF], [SHIPMAST].[SHTOPP], [SHIPMAST].[SHTYPE], [SHIPMAST].[SHPFLG], [SHIPMAST].[SHCOFL], [SHIPMAST].[SHSCRP], [SHIPMAST].[SHCUTC], [SHIPMAST].[SHIPCC], [SHIPMAST].[SHIPYY], [SHIPMAST].[SHIPMM], [SHIPMAST].[SHIPDD], [SHIPMAST].[SHRFLG], [SHIPMAST].[SHSHAP], [SHIPMAST].[SHCLS3], [SHIPMAST].[SHLDIS], [SHIPMAST].[SHINSM], [SHIPMAST].[SHSQTY], [SHIPMAST].[SHUOM], [SHIPMAST].[SHBQTY], [SHIPMAST].[SHBUOM], [SHIPMAST].[SHBINC], [SHIPMAST].[SHOQTY], [SHIPMAST].[SHOUOM], [SHIPMAST].[SHOINC], [SHIPMAST].[SHTLBS], [SHIPMAST].[SHTPCS], [SHIPMAST].[SHTFTS], [SHIPMAST].[SHTSFT], [SHIPMAST].[SHTMTR], [SHIPMAST].[SHTKG], [SHIPMAST].[SHPRCG], [SHIPMAST].[SHHAND], [SHIPMAST].[SHCDIS], [SHIPMAST].[SHCUST], [SHIPMAST].[SHTERR], [SHIPMAST].[SHOUTS], [SHIPMAST].[SHLINE], [SHIPMAST].[SHORCC], [SHIPMAST].[SHORYY], [SHIPMAST].[SHORMM], [SHIPMAST].[SHORDD], [SHIPMAST].[SHPRCC], [SHIPMAST].[SHPRYY], [SHIPMAST].[SHPRMM], [SHIPMAST].[SHPRDD], [SHIPMAST].[SHIVCC], [SHIPMAST].[SHIVYY], [SHIPMAST].[SHIVMM], [SHIPMAST].[SHIVDD], [SHIPMAST].[SHMSLS], [SHIPMAST].[SHMSLD], [SHIPMAST].[SHFSLS], [SHIPMAST].[SHFSLD], [SHIPMAST].[SHPSLS], [SHIPMAST].[SHPSLD], [SHIPMAST].[SHOSLS], [SHIPMAST].[SHOSLD], [SHIPMAST].[SHDSLS], [SHIPMAST].[SHDSLD], [SHIPMAST].[SHMCSS], [SHIPMAST].[SHMCSD], [SHIPMAST].[SHFISS], [SHIPMAST].[SHFISD], [SHIPMAST].[SHFOSS], [SHIPMAST].[SHFOSD], [SHIPMAST].[SHFSFS], [SHIPMAST].[SHFSFD], [SHIPMAST].[SHPCSS], [SHIPMAST].[SHPCSD], [SHIPMAST].[SHOCSS], [SHIPMAST].[SHOCSD], [SHIPMAST].[SHADBS], [SHIPMAST].[SHADBD], [SHIPMAST].[SHOPBS], [SHIPMAST].[SHOPBD], [SHIPMAST].[SHIAJS], [SHIPMAST].[SHIAJD], [SHIPMAST].[SHSLSS], [SHIPMAST].[SHSLSD], [SHIPMAST].[SHSWGS], [SHIPMAST].[SHSWGD], [SHIPMAST].[SHADPC], [SHIPMAST].[SHUNSP], [SHIPMAST].[SHUUOM], [SHIPMAST].[SHSAFL], [SHIPMAST].[SHSACC], [SHIPMAST].[SHSAYY], [SHIPMAST].[SHSAMM], [SHIPMAST].[SHSADD], [SHIPMAST].[SHFRGH], [SHIPMAST].[SHSCDL], [SHIPMAST].[SHSCLB], [SHIPMAST].[SHSCKG], [SHIPMAST].[SHDBDC], [SHIPMAST].[SHTRCK], [SHIPMAST].[SHODES], [SHIPMAST].[SHSHOP], [SHIPMAST].[SHSHTO], [SHIPMAST].[SHBCTY], [SHIPMAST].[SHSCTY], [SHIPMAST].[SHTMPS], [SHIPMAST].[SHSTER], [SHIPMAST].[SHTRAD], [SHIPMAST].[SHBPCC], [SHIPMAST].[SHEEC], [SHIPMAST].[SHSEC], [SHIPMAST].[SHITYP], [SHIPMAST].[SHDPTI], [SHIPMAST].[SHDPTO], [SHIPMAST].[SHDSTO], [SHIPMAST].[SHCSTO], [SHIPMAST].[SHSMDO], [SHIPMAST].[SHSLMO], [SHIPMAST].[SHICMP], [SHIPMAST].[SHADR1], [SHIPMAST].[SHADR2], [SHIPMAST].[SHADR3], [SHIPMAST].[SHCITY], [SHIPMAST].[SHSTAT], [SHIPMAST].[SHZIP], [SHIPMAST].[SHJOB]
--FROM  [SHIPMAST] [SHIPMAST]
--WHERE [SHIPMAST].[SHORDN] > 950000;'''



/*

QUERIES FROM EXCEL
                --Credit memos
                SELECT oddist*1000000+odordr, SALESMAN.SMNAME, OEOPNORD.OOTYPE, odcdis*100000+odcust, ARCUST.CALPHA, OEDETAIL.ODITEM, OEDETAIL.ODSIZ1, OEDETAIL.ODSIZ2, OEDETAIL.ODSIZ3, OEDETAIL.ODCRTD, OEDETAIL.ODTFTS, OEDETAIL.ODTLBS, OEDETAIL.ODTPCS, OEDETAIL.ODSLSX, OEDETAIL.ODFRTS, OEDETAIL.ODCSTX, OEDETAIL.ODPRCC, OEDETAIL.ODADCC, OEDETAIL.ODWCCS, ARCUST.CSTAT, ARCUST.CCTRY, OOICC*1000000+OOIYY*10000+OOIMM*100+OOIDD, OEDETAIL.ODCREF
                FROM S219EAAV.MW4FILE.ARCUST ARCUST, S219EAAV.MW4FILE.OEDETAIL OEDETAIL, S219EAAV.MW4FILE.OEOPNORD OEOPNORD, S219EAAV.MW4FILE.SALESMAN SALESMAN
                WHERE OEDETAIL.ODDIST = OEOPNORD.OODIST AND OEDETAIL.ODORDR = OEOPNORD.OOORDR AND OEOPNORD.OOCDIS = ARCUST.CDIST AND OEOPNORD.OOCUST = ARCUST.CCUST AND OEOPNORD.OOISMD = SALESMAN.SMDIST AND OEOPNORD.OOISMN = SALESMAN.SMSMAN AND ((OEOPNORD.OOTYPE='C') AND (OEOPNORD.OORECD='W') AND (ooicc*10000+ooiyy*100+ooimm Between ? And ?))

                Union open orders, order detail, customer, salesman. 
                OEDETAIL, OEOPNORD, (DISTRICT, ORDER) customer district, customer number, internal salesman
                Open order type c, open order record W

--Customer summary
SELECT DISTINCT cdist*100000+ccust, ARCUST.CALPHA, ARCUST.CLIMIT, CISMD1*100+CISLM1, CSMDI1*100+CSLMN1,SALESMAN.SMNAME
FROM S219EAAV.MW4FILE.ARCUST ARCUST, S219EAAV.MW4FILE.SALESMAN SALESMAN
WHERE ARCUST.CISMD1 = SALESMAN.SMDIST AND ARCUST.CISLM1 = SALESMAN.SMSMAN
ORDER BY ARCUST.CALPHA

--joins customer and salesman
In excel this produces monthly sales by customer and salesman
                


--Customer summary 1
SELECT DISTINCT smdist*100+smsman, SALESMAN.SMNAME
FROM MW4FILE.SALESMAN SALESMAN
--In excel this produces monthly sales by salesman


-- Query for metalnet
SELECT ITEMONHD.IORECD, ITEMONHD.IOCOMP, ITEMONHD.IODIST, ITEMONHD.IOITEM, ITEMONHD.IOQOH, ITEMONHD.IOQOR, ITEMONHD.IOQOO, ITEMONHD.IOQOOR, ITEMONHD.IOQIT, ITEMONHD.IOQHLD, ITEMONHD.IOQCOL, ITEMONHD.IOROH, ITEMONHD.IOROR, ITEMONHD.IOROO, ITEMONHD.IOROOR, ITEMONHD.IORIT, ITEMONHD.IORIQC, ITEMONHD.IOBOMI, ITEMONHD.IOBOMC, ITEMONHD.IOLCCC, ITEMONHD.IOLCYY, ITEMONHD.IOLCMM, ITEMONHD.IOLCDD, ITEMONHD.IOCUOM, ITEMONHD.IOACST, ITEMONHD.IORCST, ITEMONHD.IORLCK, ITEMONHD.IOFCST, ITEMONHD.IOSCST, ITEMONHD.IOSCCC, ITEMONHD.IOSCYY, ITEMONHD.IOSCMM, ITEMONHD.IOSCDD, ITEMONHD.IODOSC, ITEMONHD.IODOSL, ITEMONHD.IOMNRQ, ITEMONHD.IOTORQ, ITEMONHD.IOPYIB, ITEMONHD.IOCYIB, ITEMONHD.IOCYIU, ITEMONHD.IOITST, ITEMONHD.IOPLVL, ITEMONHD.IOBGIN, ITEMONHD.IOMNBL, ITEMONHD.IOROPT, ITEMONHD.IOROPL, ITEMONHD.IOROQT, ITEMONHD.IOLDTM, ITEMONHD.IOBUY, ITEMONHD.IOBGIT, ITEMONHD.IOROFC, ITEMONHD.IOSSTK, ITEMONHD.IOLDTL, ITEMONHD.IOINVC, ITEMONHD.IOMTST, ITEMONHD.IODISC, ITEMONHD.IOOWNF, ITEMONHD.IONSDC, ITEMONHD.IO1RCT, ITEMONHD.IOTOPP, ITEMONHD.IOPMON, ITEMONHD.IOLOCC, ITEMONHD.IOLOYY, ITEMONHD.IOLOMM, ITEMONHD.IOLODD, ITEMONHD.IO1ACQ, ITEMONHD.IOLFB1, ITEMONHD.IOLFB2, ITEMONHD.IOCMNT, ITEMONHD.IOMSLS, ITEMONHD.IOYSLS, ITEMONHD.IOMCST, ITEMONHD.IOYCST, ITEMONHD.IOMUNT, ITEMONHD.IOYUNT, ITEMONHD.IOMWGT, ITEMONHD.IOYWGT, ITEMONHD.IODLCC, ITEMONHD.IODLYY, ITEMONHD.IODLMM, ITEMONHD.IODLDD, ITEMONHD.IOPUOM, ITEMONHD.IOCNTP, ITEMONHD.IOCNTL, ITEMONHD.IOBPRC, ITEMONHD.IOBPRL, ITEMONHD.IOBPCC, ITEMONHD.IOBPYY, ITEMONHD.IOBPMM, ITEMONHD.IOBPDD, ITEMONHD.IOCNTC, ITEMONHD.IOCDIS, ITEMONHD.IOCUST, ITEMONHD.IOMACN, ITEMONHD.IOPRCD, ITEMONHD.IORUNR, ITEMONHD.IORUOM, ITEMONHD.IOMEIF, ITEMONHD.IOORDI, ITEMONHD.IOMDIF, ITEMONHD.IOPMCC, ITEMONHD.IOPMYY, ITEMONHD.IOPMMM, ITEMONHD.IOPMDD, ITEMONHD.IOPMCD, ITEMONHD.IOLRCS, ITEMONHD.IOZ, ITEMONHD.IOC, ITEMONHD.IOD, ITEMONHD.IOPCTF, ITEMONHD.IOOUOM, ITEMONHD.IOMAGA, ITEMONHD.IOHURD, ITEMONHD.IOATAJ, ITEMONHD.IOLPCC, ITEMONHD.IOLPYY, ITEMONHD.IOLPMM, ITEMONHD.IOLPDD, ITEMONHD.IOLPUS, ITEMONHD.IOLSCC, ITEMONHD.IOLSYY, ITEMONHD.IOLSMM, ITEMONHD.IOLSDD, ITEMONHD.IOLSUS, ITEMONHD.IOLMCC, ITEMONHD.IOLMYY, ITEMONHD.IOLMMM, ITEMONHD.IOLMDD, ITEMONHD.IOLMUS, ITEMONHD.IOCLS3, ITEMONHD.IOSBCL, ITEMONHD.IOSTCL, ITEMONHD.IOPUSD, ITEMONHD.IOPUSQ, ITEMONHD.IOPCST, ITEMONHD.IOPSLS, ITEMONHD.IOPUNT, ITEMONHD.IOPLBS, ITEMONHD.IOPATN, ITEMONHD.IOMOST, ITEMONHD.IOBOMW, ITEMONHD.IOAVMS, ITEMONHD.IOAVLB, ITEMONHD.IOAVOH, ITEMONHD.IOAVOS, ITEMONHD.IOUSQT, ITEMONHD.IOUSDL, ITEMONHD.IOYTDL, ITEMONHD.IOLIFO, ITEMONHD.IOSRCE, ITEMONHD.IOSUCC, ITEMONHD.IOSUYY, ITEMONHD.IOSUMM, ITEMONHD.IOSUDD, ITEMONHD.IOOPPO, ITEMONHD.IOOPPD, ITEMONHD.IOTSTR, ITEMONHD.IOAVMQ, ITEMONHD.IOITDL, ITEMONHD.IOITUN, ITEMONHD.IORSTK, ITEMONHD.IORSMP, ITEMONHD.IOHFRR, ITEMONHD.IOCORS, ITEMONHD.IOTRRS, ITEMONHD.IOMPRS, ITEMONHD.IOSTOR, ITEMONHD.IOASOR, ITEMONHD.IOAVG3, ITEMONHD.IOAV12, ITEMONHD.IOPICC, ITEMONHD.IOPIYY, ITEMONHD.IOPIMM, ITEMONHD.IOPIDD, ITEMONHD.IOPDSC, ITEMONHD.IOITRM, ITEMONHD.IOLPMC, ITEMONHD.IOLPML, ITEMONHD.IOCPMC, ITEMONHD.IOCPML, ITEMONHD.IODSPS, ITEMONHD.IOSPCD, ITEMONHD.IOPRC2, ITEMONHD.IOSALE, ITEMONHD.IOQQTY, ITEMONHD.IOQAC, ITEMONHD.IOOELK, ITEMONHD.IOMPLK, ITEMONHD.IOABCP, ITEMONHD.IOANRS, ITEMONHD.IOTAX, ITEMONHD.IORBCS, ITEMONHD.IOTUNA
FROM S219EAAV.MW4FILE.ITEMONHD ITEMONHD
-- Crazy.. in excel is liked to price

*/

/*
-- Salesorders
SELECT oddist*1000000+odordr, SALESMAN.SMNAME, OEOPNORD.OOTYPE, odcdis*100000+odcust, ARCUST.CALPHA, OOICC*1000000+OOIYY*10000+OOIMM*100+OOIDD, OEDETAIL.ODITEM, OEDETAIL.ODSIZ1, OEDETAIL.ODSIZ2, OEDETAIL.ODSIZ3, OEDETAIL.ODCRTD, SLSDSCOV.DXDSC2, OEDETAIL.ODTFTS, OEDETAIL.ODTLBS, OEDETAIL.ODTPCS, OEDETAIL.ODSLSX, OEDETAIL.ODFRTS, OEDETAIL.ODCSTX, OEDETAIL.ODPRCC, OEDETAIL.ODADCC, OEDETAIL.ODWCCS, ARCUST.CSTAT, ARCUST.CCTRY
FROM S219EAAV.MW4FILE.ARCUST ARCUST, S219EAAV.MW4FILE.OEDETAIL OEDETAIL, S219EAAV.MW4FILE.OEOPNORD OEOPNORD, S219EAAV.MW4FILE.SALESMAN SALESMAN, S219EAAV.MW4FILE.SLSDSCOV SLSDSCOV
WHERE OEDETAIL.ODDIST = OEOPNORD.OODIST AND OEDETAIL.ODDIST = SLSDSCOV.DXDIST AND OEDETAIL.ODMLIN = SLSDSCOV.DXMLIN AND OEDETAIL.ODORDR = OEOPNORD.OOORDR AND OEDETAIL.ODORDR = SLSDSCOV.DXORDR AND OEOPNORD.OOCDIS = ARCUST.CDIST AND OEOPNORD.OOCUST = ARCUST.CCUST AND OEOPNORD.OOISMD = SALESMAN.SMDIST AND OEOPNORD.OOISMN = SALESMAN.SMSMAN AND ((OEOPNORD.OOTYPE In ('A','B')) AND (OEOPNORD.OORECD='W') AND (ooicc*10000+ooiyy*100+ooimm Between ? And ?))
--In excel -- Order, invoiced, salesman, customer, so... orders



--SPO
SELECT oddist*1000000+odordr, SALESMAN.SMNAME, OEOPNORD.OOTYPE, odcdis*100000+odcust, ARCUST.CALPHA, ooicc*100+ooiyy, OEOPNORD.OOIMM, OEOPNORD.OOIDD, OEDETAIL.ODITEM, SPHEADER.BSSVEN, SPHEADER.BSSPS#
FROM S219EAAV.MW4FILE.ARCUST ARCUST, S219EAAV.MW4FILE.OEDETAIL OEDETAIL, S219EAAV.MW4FILE.OEOPNORD OEOPNORD, S219EAAV.MW4FILE.SALESMAN SALESMAN, S219EAAV.MW4FILE.SPHEADER SPHEADER
WHERE OEDETAIL.ODDIST = OEOPNORD.OODIST AND OEDETAIL.ODORDR = OEOPNORD.OOORDR AND OEOPNORD.OOCDIS = ARCUST.CDIST AND OEOPNORD.OOCUST = ARCUST.CCUST AND OEOPNORD.OOISMD = SALESMAN.SMDIST AND OEOPNORD.OOISMN = SALESMAN.SMSMAN AND OEDETAIL.ODDIST = SPHEADER.BSDIST AND OEDETAIL.ODORDR = SPHEADER.BSORDR AND ((OEOPNORD.OOTYPE In ('A','B')) AND (OEOPNORD.OORECD='W') AND (OEDETAIL.ODDIST=1) AND (OEDETAIL.ODORDR>?))

*/









