/*****************************************
*****************************************/
--ROP_query_
-- Price	
--Comment about the type of data it will retrieve
 SELECT ITEMONHD.IOITEM, ITEMONHD.IOBPRC
FROM S219EAAV.MW4FILE.ITEMONHD ITEMONHD

/*****************************************
*****************************************/
--ROP_query_
--Material Processing	
SELECT MPDETAIL.MDORDR, APVEND.VVNDR, APVEND.VALPHA, MPDETAIL.MDCLOS, MPDETAIL.MDITEM, MPDETAIL.MDCRTD, mdrqcc*1000000+mdrqyy*10000+mdrqmm*100+mdrqdd, MPDETAIL.MDOQTY, MPDETAIL.MDOUOM, MPDETAIL.MDIQTY
FROM S219EAAV.MW4FILE.APVEND APVEND, S219EAAV.MW4FILE.MPDETAIL MPDETAIL
WHERE APVEND.VCOMP = MPDETAIL.MDCOMP AND APVEND.VVNDR = MPDETAIL.MDVNDR
ORDER BY MPDETAIL.MDITEM, MPDETAIL.MDORDR DESC

/*****************************************
*****************************************/
--ROP_query_
--PO query	
SELECT PODETAIL.BDPONO, PODETAIL.BDVNDR, APVEND.VNAME, PODETAIL.BDRECD, PODETAIL.BDITEM, PODETAIL.BDCRTD, bdrpcc*1000000+bdrpyy*10000+bdrpmm*100+bdrpdd, PODETAIL.BDOQOO, PODETAIL.BDIUOM, PODETAIL.BDCQOO, PODETAIL.BDOOQ, PODETAIL.BDTIQR, bdpocc*1000000+bdpoyy*10000+bdpomm*100+bdpodd, bdrccc*1000000+bdrcyy*10000+bdrcmm*100+bdrcdd
FROM {oj S219EAAV.MW4FILE.PODETAIL PODETAIL LEFT OUTER JOIN S219EAAV.MW4FILE.APVEND APVEND ON PODETAIL.BDVNDR = APVEND.VVNDR}
WHERE (PODETAIL.BDITEM Between '50000' And '99998')
ORDER BY PODETAIL.BDITEM, PODETAIL.BDPONO DESC

/*****************************************
*****************************************/
----ROP_query_
--ROP Query	
SELECT ITEMMAST.IMFSP2, ITEMMAST.IMITEM, ITEMMAST.IMSIZ1, ITEMMAST.IMSIZ2, ITEMMAST.IMSIZ3, ITEMMAST.IMDSC2, ITEMMAST.IMWPFT, ITEMONHD.IOACST, ITEMONHD.IOQOH, ITEMONHD.IOQOO, IOQOR+IOQOOR, ITEMMAST.IMDSC1, ITEMMAST.IMWUOM, ITEMMAST.IMCSMO
FROM S219EAAV.MW4FILE.ITEMMAST ITEMMAST, S219EAAV.MW4FILE.ITEMONHD ITEMONHD
WHERE ITEMONHD.IOITEM = ITEMMAST.IMITEM AND ((ITEMMAST.IMRECD='A') AND (ITEMMAST.IMITEM Between '49999' And '90000'))
ORDER BY ITEMMAST.IMFSP2

/*****************************************
*****************************************/
--ROP_query_
--Sales Data	
SELECT OEOPNORD.OORECD, OEDETAIL.ODTYPE, OEDETAIL.ODITEM, OEDETAIL.ODORDR, OEOPNORD.OOCUST, ARCUST.CALPHA, OEDETAIL.ODTLBS, OEDETAIL.ODTFTS, ooocc*1000000+oooyy*10000+ooomm*100+ooodd, csmdi1*100+cslmn1
FROM S219EAAV.MW4FILE.ARCUST ARCUST, S219EAAV.MW4FILE.OEDETAIL OEDETAIL, S219EAAV.MW4FILE.OEOPNORD OEOPNORD
WHERE OEDETAIL.ODORDR = OEOPNORD.OOORDR AND OEOPNORD.OOCUST = ARCUST.CCUST AND ((OEOPNORD.OORECD='A') AND (OEDETAIL.ODTYPE In ('A','C')))
ORDER BY OEDETAIL.ODITEM

/*****************************************
*****************************************/
--ROP_query_
--Tag Query	
SELECT ITEMTAG.ITITEM, ITEMTAG.ITTAG, ITEMTAG.ITTDES, ITEMTAG.ITLNTH, ITEMTAG.ITTPCS, ITEMTAG.ITHEAT, ITEMTAG.ITV301, ITEMTAG.ITLOCT, ITEMTAG.ITTQTY, ITEMTAG.ITRQTY, ITEMMAST.IMFSP2
FROM S219EAAV.MW4FILE.ITEMMAST ITEMMAST, S219EAAV.MW4FILE.ITEMTAG ITEMTAG
WHERE ITEMTAG.ITITEM = ITEMMAST.IMITEM AND ((ITEMTAG.ITRECD='A') AND (ITEMTAG.ITITEM>'49999'))
ORDER BY ITEMTAG.ITITEM, ITEMTAG.ITHEAT, ITEMTAG.ITV301, ITEMTAG.ITLNTH

/*****************************************
*****************************************/
-- ROP_query_
-- Usage Query	
-- This query retrieves historical item usage data based on transaction dates and item ranges.
SELECT ITEMHIST.IHITEM, ITEMHIST.IHTRNT, ITEMHIST.IHTRN#, ITEMHIST.IHVNDR, ITEMHIST.IHCUST, ITEMHIST.IHTRYY, ITEMHIST.IHTRMM, ITEMHIST.IHTRDD, ITEMHIST.IHTQTY
FROM S219EAAV.MW4FILE.ITEMHIST ITEMHIST
WHERE (ihtrcc*1000000+ihtryy*10000+ihtrmm*100+ihtrdd>?) AND (ITEMHIST.IHITEM Between '50000' And '99998')
ORDER BY ITEMHIST.IHITEM, ITEMHIST.IHTRYY, ITEMHIST.IHTRMM, ITEMHIST.IHTRDD

/*****************************************
*****************************************/
-- ROP_query_
-- Usage sum query
-- This query calculates the sum of usage for items within a specific range and date.	
SELECT DISTINCT ITEMHIST.IHITEM, ITEMHIST.IHTRNT, ITEMHIST.IHCUST, ARCUST.CALPHA, csmdi1*100+cslmn1
FROM S219EAAV.MW4FILE.ARCUST ARCUST, S219EAAV.MW4FILE.ITEMHIST ITEMHIST
WHERE ARCUST.CCUST = ITEMHIST.IHCUST AND ((ihtrcc*1000000+ihtryy*10000+ihtrmm*100+ihtrdd>?) AND (ITEMHIST.IHITEM Between '50000' And '99998') AND (ITEMHIST.IHTRNT In ('CR','IN')))
ORDER BY ITEMHIST.IHITEM, ARCUST.CALPHA
FS_query	No query on the FS file

/*****************************************
*****************************************/
-- This section of the SQL script is related to sales analysis queries.
-- Specifically, it includes a placeholder for analyzing credit memos (CreditMemos).
-- Credit memos are typically used for financial adjustments, refunds, or corrections in sales transactions.
-- Ensure that the queries in this section are well-defined and optimized for accurate analysis.
--SalesAnalisysQuery_
--CreditMemos	
SELECT oddist*1000000+odordr, SALESMAN.SMNAME, OEOPNORD.OOTYPE, odcdis*100000+odcust, ARCUST.CALPHA, OEDETAIL.ODITEM, OEDETAIL.ODSIZ1, OEDETAIL.ODSIZ2, OEDETAIL.ODSIZ3, OEDETAIL.ODCRTD, OEDETAIL.ODTFTS, OEDETAIL.ODTLBS, OEDETAIL.ODTPCS, OEDETAIL.ODSLSX, OEDETAIL.ODFRTS, OEDETAIL.ODCSTX, OEDETAIL.ODPRCC, OEDETAIL.ODADCC, OEDETAIL.ODWCCS, ARCUST.CSTAT, ARCUST.CCTRY, OOICC*1000000+OOIYY*10000+OOIMM*100+OOIDD, OEDETAIL.ODCREF
FROM S219EAAV.MW4FILE.ARCUST ARCUST, S219EAAV.MW4FILE.OEDETAIL OEDETAIL, S219EAAV.MW4FILE.OEOPNORD OEOPNORD, S219EAAV.MW4FILE.SALESMAN SALESMAN
WHERE OEDETAIL.ODDIST = OEOPNORD.OODIST AND OEDETAIL.ODORDR = OEOPNORD.OOORDR AND OEOPNORD.OOCDIS = ARCUST.CDIST AND OEOPNORD.OOCUST = ARCUST.CCUST AND OEOPNORD.OOISMD = SALESMAN.SMDIST AND OEOPNORD.OOISMN = SALESMAN.SMSMAN AND ((OEOPNORD.OOTYPE='C') AND (OEOPNORD.OORECD='W') AND (ooicc*10000+ooiyy*100+ooimm Between ? And ?))

/*****************************************
*****************************************/
--SalesAnalisysQuery_
--Customer-Summary	
SELECT DISTINCT cdist*100000+ccust, ARCUST.CALPHA, ARCUST.CLIMIT, CISMD1*100+CISLM1, CSMDI1*100+CSLMN1,SALESMAN.SMNAME
FROM S219EAAV.MW4FILE.ARCUST ARCUST, S219EAAV.MW4FILE.SALESMAN SALESMAN
WHERE ARCUST.CISMD1 = SALESMAN.SMDIST AND ARCUST.CISLM1 = SALESMAN.SMSMAN
ORDER BY ARCUST.CALPHA

/*****************************************
*****************************************/
--SalesAnalisysQuery_
--Customer-Summary1	SELECT DISTINCT smdist*100+smsman, SALESMAN.SMNAME
FROM MW4FILE.SALESMAN SALESMAN

/*****************************************
*****************************************/
--SalesAnalisysQuery_
--QueryFromMetalNet1	
SELECT ITEMONHD.IORECD, ITEMONHD.IOCOMP, ITEMONHD.IODIST, ITEMONHD.IOITEM, ITEMONHD.IOQOH, ITEMONHD.IOQOR, ITEMONHD.IOQOO, ITEMONHD.IOQOOR, ITEMONHD.IOQIT, ITEMONHD.IOQHLD, ITEMONHD.IOQCOL, ITEMONHD.IOROH, ITEMONHD.IOROR, ITEMONHD.IOROO, ITEMONHD.IOROOR, ITEMONHD.IORIT, ITEMONHD.IORIQC, ITEMONHD.IOBOMI, ITEMONHD.IOBOMC, ITEMONHD.IOLCCC, ITEMONHD.IOLCYY, ITEMONHD.IOLCMM, ITEMONHD.IOLCDD, ITEMONHD.IOCUOM, ITEMONHD.IOACST, ITEMONHD.IORCST, ITEMONHD.IORLCK, ITEMONHD.IOFCST, ITEMONHD.IOSCST, ITEMONHD.IOSCCC, ITEMONHD.IOSCYY, ITEMONHD.IOSCMM, ITEMONHD.IOSCDD, ITEMONHD.IODOSC, ITEMONHD.IODOSL, ITEMONHD.IOMNRQ, ITEMONHD.IOTORQ, ITEMONHD.IOPYIB, ITEMONHD.IOCYIB, ITEMONHD.IOCYIU, ITEMONHD.IOITST, ITEMONHD.IOPLVL, ITEMONHD.IOBGIN, ITEMONHD.IOMNBL, ITEMONHD.IOROPT, ITEMONHD.IOROPL, ITEMONHD.IOROQT, ITEMONHD.IOLDTM, ITEMONHD.IOBUY, ITEMONHD.IOBGIT, ITEMONHD.IOROFC, ITEMONHD.IOSSTK, ITEMONHD.IOLDTL, ITEMONHD.IOINVC, ITEMONHD.IOMTST, ITEMONHD.IODISC, ITEMONHD.IOOWNF, ITEMONHD.IONSDC, ITEMONHD.IO1RCT, ITEMONHD.IOTOPP, ITEMONHD.IOPMON, ITEMONHD.IOLOCC, ITEMONHD.IOLOYY, ITEMONHD.IOLOMM, ITEMONHD.IOLODD, ITEMONHD.IO1ACQ, ITEMONHD.IOLFB1, ITEMONHD.IOLFB2, ITEMONHD.IOCMNT, ITEMONHD.IOMSLS, ITEMONHD.IOYSLS, ITEMONHD.IOMCST, ITEMONHD.IOYCST, ITEMONHD.IOMUNT, ITEMONHD.IOYUNT, ITEMONHD.IOMWGT, ITEMONHD.IOYWGT, ITEMONHD.IODLCC, ITEMONHD.IODLYY, ITEMONHD.IODLMM, ITEMONHD.IODLDD, ITEMONHD.IOPUOM, ITEMONHD.IOCNTP, ITEMONHD.IOCNTL, ITEMONHD.IOBPRC, ITEMONHD.IOBPRL, ITEMONHD.IOBPCC, ITEMONHD.IOBPYY, ITEMONHD.IOBPMM, ITEMONHD.IOBPDD, ITEMONHD.IOCNTC, ITEMONHD.IOCDIS, ITEMONHD.IOCUST, ITEMONHD.IOMACN, ITEMONHD.IOPRCD, ITEMONHD.IORUNR, ITEMONHD.IORUOM, ITEMONHD.IOMEIF, ITEMONHD.IOORDI, ITEMONHD.IOMDIF, ITEMONHD.IOPMCC, ITEMONHD.IOPMYY, ITEMONHD.IOPMMM, ITEMONHD.IOPMDD, ITEMONHD.IOPMCD, ITEMONHD.IOLRCS, ITEMONHD.IOZ, ITEMONHD.IOC, ITEMONHD.IOD, ITEMONHD.IOPCTF, ITEMONHD.IOOUOM, ITEMONHD.IOMAGA, ITEMONHD.IOHURD, ITEMONHD.IOATAJ, ITEMONHD.IOLPCC, ITEMONHD.IOLPYY, ITEMONHD.IOLPMM, ITEMONHD.IOLPDD, ITEMONHD.IOLPUS, ITEMONHD.IOLSCC, ITEMONHD.IOLSYY, ITEMONHD.IOLSMM, ITEMONHD.IOLSDD, ITEMONHD.IOLSUS, ITEMONHD.IOLMCC, ITEMONHD.IOLMYY, ITEMONHD.IOLMMM, ITEMONHD.IOLMDD, ITEMONHD.IOLMUS, ITEMONHD.IOCLS3, ITEMONHD.IOSBCL, ITEMONHD.IOSTCL, ITEMONHD.IOPUSD, ITEMONHD.IOPUSQ, ITEMONHD.IOPCST, ITEMONHD.IOPSLS, ITEMONHD.IOPUNT, ITEMONHD.IOPLBS, ITEMONHD.IOPATN, ITEMONHD.IOMOST, ITEMONHD.IOBOMW, ITEMONHD.IOAVMS, ITEMONHD.IOAVLB, ITEMONHD.IOAVOH, ITEMONHD.IOAVOS, ITEMONHD.IOUSQT, ITEMONHD.IOUSDL, ITEMONHD.IOYTDL, ITEMONHD.IOLIFO, ITEMONHD.IOSRCE, ITEMONHD.IOSUCC, ITEMONHD.IOSUYY, ITEMONHD.IOSUMM, ITEMONHD.IOSUDD, ITEMONHD.IOOPPO, ITEMONHD.IOOPPD, ITEMONHD.IOTSTR, ITEMONHD.IOAVMQ, ITEMONHD.IOITDL, ITEMONHD.IOITUN, ITEMONHD.IORSTK, ITEMONHD.IORSMP, ITEMONHD.IOHFRR, ITEMONHD.IOCORS, ITEMONHD.IOTRRS, ITEMONHD.IOMPRS, ITEMONHD.IOSTOR, ITEMONHD.IOASOR, ITEMONHD.IOAVG3, ITEMONHD.IOAV12, ITEMONHD.IOPICC, ITEMONHD.IOPIYY, ITEMONHD.IOPIMM, ITEMONHD.IOPIDD, ITEMONHD.IOPDSC, ITEMONHD.IOITRM, ITEMONHD.IOLPMC, ITEMONHD.IOLPML, ITEMONHD.IOCPMC, ITEMONHD.IOCPML, ITEMONHD.IODSPS, ITEMONHD.IOSPCD, ITEMONHD.IOPRC2, ITEMONHD.IOSALE, ITEMONHD.IOQQTY, ITEMONHD.IOQAC, ITEMONHD.IOOELK, ITEMONHD.IOMPLK, ITEMONHD.IOABCP, ITEMONHD.IOANRS, ITEMONHD.IOTAX, ITEMONHD.IORBCS, ITEMONHD.IOTUNA
FROM S219EAAV.MW4FILE.ITEMONHD ITEMONHD

/*****************************************
*****************************************/
--SalesAnalisysQuery
--SalesOrders	
SELECT oddist*1000000+odordr, SALESMAN.SMNAME, OEOPNORD.OOTYPE, odcdis*100000+odcust, ARCUST.CALPHA, OOICC*1000000+OOIYY*10000+OOIMM*100+OOIDD, OEDETAIL.ODITEM, OEDETAIL.ODSIZ1, OEDETAIL.ODSIZ2, OEDETAIL.ODSIZ3, OEDETAIL.ODCRTD, SLSDSCOV.DXDSC2, OEDETAIL.ODTFTS, OEDETAIL.ODTLBS, OEDETAIL.ODTPCS, OEDETAIL.ODSLSX, OEDETAIL.ODFRTS, OEDETAIL.ODCSTX, OEDETAIL.ODPRCC, OEDETAIL.ODADCC, OEDETAIL.ODWCCS, ARCUST.CSTAT, ARCUST.CCTRY
FROM S219EAAV.MW4FILE.ARCUST ARCUST, S219EAAV.MW4FILE.OEDETAIL OEDETAIL, S219EAAV.MW4FILE.OEOPNORD OEOPNORD, S219EAAV.MW4FILE.SALESMAN SALESMAN, S219EAAV.MW4FILE.SLSDSCOV SLSDSCOV
WHERE OEDETAIL.ODDIST = OEOPNORD.OODIST AND OEDETAIL.ODDIST = SLSDSCOV.DXDIST AND OEDETAIL.ODMLIN = SLSDSCOV.DXMLIN AND OEDETAIL.ODORDR = OEOPNORD.OOORDR AND OEDETAIL.ODORDR = SLSDSCOV.DXORDR AND OEOPNORD.OOCDIS = ARCUST.CDIST AND OEOPNORD.OOCUST = ARCUST.CCUST AND OEOPNORD.OOISMD = SALESMAN.SMDIST AND OEOPNORD.OOISMN = SALESMAN.SMSMAN AND ((OEOPNORD.OOTYPE In ('A','B')) AND (OEOPNORD.OORECD='W') AND (ooicc*10000+ooiyy*100+ooimm Between ? And ?))

/*****************************************
*****************************************/
--SalesAnalisysQuery_
--SPO	
SELECT oddist*1000000+odordr, SALESMAN.SMNAME, OEOPNORD.OOTYPE, odcdis*100000+odcust, ARCUST.CALPHA, ooicc*100+ooiyy, OEOPNORD.OOIMM, OEOPNORD.OOIDD, OEDETAIL.ODITEM, SPHEADER.BSSVEN, SPHEADER.BSSPS#
FROM S219EAAV.MW4FILE.ARCUST ARCUST, S219EAAV.MW4FILE.OEDETAIL OEDETAIL, S219EAAV.MW4FILE.OEOPNORD OEOPNORD, S219EAAV.MW4FILE.SALESMAN SALESMAN, S219EAAV.MW4FILE.SPHEADER SPHEADER
WHERE OEDETAIL.ODDIST = OEOPNORD.OODIST AND OEDETAIL.ODORDR = OEOPNORD.OOORDR AND OEOPNORD.OOCDIS = ARCUST.CDIST AND OEOPNORD.OOCUST = ARCUST.CCUST AND OEOPNORD.OOISMD = SALESMAN.SMDIST AND OEOPNORD.OOISMN = SALESMAN.SMSMAN AND OEDETAIL.ODDIST = SPHEADER.BSDIST AND OEDETAIL.ODORDR = SPHEADER.BSORDR AND ((OEOPNORD.OOTYPE In ('A','B')) AND (OEOPNORD.OORECD='W') AND (OEDETAIL.ODDIST=1) AND (OEDETAIL.ODORDR>?))

/*****************************************
*****************************************/
--Shipmast_
--QueryfromMetalNet	
SELECT SHIPMAST.SHRECD, SHIPMAST.SHCOMP, SHIPMAST.SHDIST, SHIPMAST.SHORDN, SHIPMAST.SHCORD, SHIPMAST.SHOREL, SHIPMAST.SHITEM, SHIPMAST.SHMDIF, SHIPMAST.SHTOPP, SHIPMAST.SHTYPE, SHIPMAST.SHPFLG, SHIPMAST.SHCOFL, SHIPMAST.SHSCRP, SHIPMAST.SHCUTC, SHIPMAST.SHIPCC, SHIPMAST.SHIPYY, SHIPMAST.SHIPMM, SHIPMAST.SHIPDD, SHIPMAST.SHRFLG, SHIPMAST.SHSHAP, SHIPMAST.SHCLS3, SHIPMAST.SHLDIS, SHIPMAST.SHINSM, SHIPMAST.SHSQTY, SHIPMAST.SHUOM, SHIPMAST.SHBQTY, SHIPMAST.SHBUOM, SHIPMAST.SHBINC, SHIPMAST.SHOQTY, SHIPMAST.SHOUOM, SHIPMAST.SHOINC, SHIPMAST.SHTLBS, SHIPMAST.SHTPCS, SHIPMAST.SHTFTS, SHIPMAST.SHTSFT, SHIPMAST.SHTMTR, SHIPMAST.SHTKG, SHIPMAST.SHPRCG, SHIPMAST.SHHAND, SHIPMAST.SHCDIS, SHIPMAST.SHCUST, SHIPMAST.SHTERR, SHIPMAST.SHOUTS, SHIPMAST.SHLINE, SHIPMAST.SHORCC, SHIPMAST.SHORYY, SHIPMAST.SHORMM, SHIPMAST.SHORDD, SHIPMAST.SHPRCC, SHIPMAST.SHPRYY, SHIPMAST.SHPRMM, SHIPMAST.SHPRDD, SHIPMAST.SHIVCC, SHIPMAST.SHIVYY, SHIPMAST.SHIVMM, SHIPMAST.SHIVDD, SHIPMAST.SHMSLS, SHIPMAST.SHMSLD, SHIPMAST.SHFSLS, SHIPMAST.SHFSLD, SHIPMAST.SHPSLS, SHIPMAST.SHPSLD, SHIPMAST.SHOSLS, SHIPMAST.SHOSLD, SHIPMAST.SHDSLS, SHIPMAST.SHDSLD, SHIPMAST.SHMCSS, SHIPMAST.SHMCSD, SHIPMAST.SHFISS, SHIPMAST.SHFISD, SHIPMAST.SHFOSS, SHIPMAST.SHFOSD, SHIPMAST.SHFSFS, SHIPMAST.SHFSFD, SHIPMAST.SHPCSS, SHIPMAST.SHPCSD, SHIPMAST.SHOCSS, SHIPMAST.SHOCSD, SHIPMAST.SHADBS, SHIPMAST.SHADBD, SHIPMAST.SHOPBS, SHIPMAST.SHOPBD, SHIPMAST.SHIAJS, SHIPMAST.SHIAJD, SHIPMAST.SHSLSS, SHIPMAST.SHSLSD, SHIPMAST.SHSWGS, SHIPMAST.SHSWGD, SHIPMAST.SHADPC, SHIPMAST.SHUNSP, SHIPMAST.SHUUOM, SHIPMAST.SHSAFL, SHIPMAST.SHSACC, SHIPMAST.SHSAYY, SHIPMAST.SHSAMM, SHIPMAST.SHSADD, SHIPMAST.SHFRGH, SHIPMAST.SHSCDL, SHIPMAST.SHSCLB, SHIPMAST.SHSCKG, SHIPMAST.SHDBDC, SHIPMAST.SHTRCK, SHIPMAST.SHODES, SHIPMAST.SHSHOP, SHIPMAST.SHSHTO, SHIPMAST.SHBCTY, SHIPMAST.SHSCTY, SHIPMAST.SHTMPS, SHIPMAST.SHSTER, SHIPMAST.SHTRAD, SHIPMAST.SHBPCC, SHIPMAST.SHEEC, SHIPMAST.SHSEC, SHIPMAST.SHITYP, SHIPMAST.SHDPTI, SHIPMAST.SHDPTO, SHIPMAST.SHDSTO, SHIPMAST.SHCSTO, SHIPMAST.SHSMDO, SHIPMAST.SHSLMO, SHIPMAST.SHICMP, SHIPMAST.SHADR1, SHIPMAST.SHADR2, SHIPMAST.SHADR3, SHIPMAST.SHCITY, SHIPMAST.SHSTAT, SHIPMAST.SHZIP, SHIPMAST.SHJOB
FROM S219EAAV.MW4FILE.SHIPMAST SHIPMAST
WHERE (SHIPMAST.SHORDN>950000)

/*****************************************
*****************************************/